<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Paul NESTOUR et Lucas LE DREVO">

<title>Data da vezañ tretet - Dossier d’Évaluation des Actifs Financiers</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Data da vezañ tretet</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Mon blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">À propos de moi</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/paulnest"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Dossier d’Évaluation des Actifs Financiers</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Paul NESTOUR et Lucas LE DREVO </p>
            </div>
    </div>
      
    
      
    </div>
    
  <div>
    <div class="abstract">
      <div class="block-title">Abstract</div>
      Nous avons réalisé ce dossier d’évaluation des actifs financiers, dans le cadre du programme de <strong>Master 1 Économétrie Appliquée</strong>, matière dispensée par <strong>M. Yayi</strong>.
    </div>
  </div>
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exercice-1-calcul-de-rendements-statistiques-usuelles-et-performance-des-titres" id="toc-exercice-1-calcul-de-rendements-statistiques-usuelles-et-performance-des-titres" class="nav-link" data-scroll-target="#exercice-1-calcul-de-rendements-statistiques-usuelles-et-performance-des-titres">Exercice 1 : Calcul de rendements, statistiques usuelles et performance des titres</a>
  <ul>
  <li><a href="#calculer-et-représenter-les-prix-et-les-rendements-de-chacun-des-fonds-en-fonction-du-temps.-commentez-les-résultats." id="toc-calculer-et-représenter-les-prix-et-les-rendements-de-chacun-des-fonds-en-fonction-du-temps.-commentez-les-résultats." class="nav-link" data-scroll-target="#calculer-et-représenter-les-prix-et-les-rendements-de-chacun-des-fonds-en-fonction-du-temps.-commentez-les-résultats.">1. Calculer et représenter les prix et les rendements de chacun des fonds en fonction du temps. Commentez les résultats.</a>
  <ul class="collapse">
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#quelles-sont-les-propriétés-financières-de-chacune-des-séries" id="toc-quelles-sont-les-propriétés-financières-de-chacune-des-séries" class="nav-link" data-scroll-target="#quelles-sont-les-propriétés-financières-de-chacune-des-séries">2. Quelles sont les propriétés financières de chacune des séries ?</a></li>
  <li><a href="#y-a-t-il-des-retours-à-la-moyenne-pouvez-vous-identifier-des-événements-dactualité-qui-pourraient-expliquer-des-valeurs-inhabituelles" id="toc-y-a-t-il-des-retours-à-la-moyenne-pouvez-vous-identifier-des-événements-dactualité-qui-pourraient-expliquer-des-valeurs-inhabituelles" class="nav-link" data-scroll-target="#y-a-t-il-des-retours-à-la-moyenne-pouvez-vous-identifier-des-événements-dactualité-qui-pourraient-expliquer-des-valeurs-inhabituelles">3. Y a-t-il des retours à la moyenne ? Pouvez-vous identifier des événements d’actualité qui pourraient expliquer des valeurs inhabituelles ?</a>
  <ul class="collapse">
  <li><a href="#conclusion-1" id="toc-conclusion-1" class="nav-link" data-scroll-target="#conclusion-1">Conclusion</a></li>
  </ul></li>
  <li><a href="#représentez-les-boites-à-moustaches-associées-à-la-distribution-de-chaque-fonds.-commentez." id="toc-représentez-les-boites-à-moustaches-associées-à-la-distribution-de-chaque-fonds.-commentez." class="nav-link" data-scroll-target="#représentez-les-boites-à-moustaches-associées-à-la-distribution-de-chaque-fonds.-commentez.">4. Représentez les boites à moustaches associées à la distribution de chaque fonds. Commentez.</a>
  <ul class="collapse">
  <li><a href="#conclusion-2" id="toc-conclusion-2" class="nav-link" data-scroll-target="#conclusion-2">Conclusion</a></li>
  </ul></li>
  <li><a href="#calculer-les-statistiques-descriptives-univariées-moyenne-variance-écart-type-asymétrie-kurtosis-pour-chaque-fonds-et-commenter-les-résultats.-quels-fonds-ont-le-rendement-moyen-le-plus-élevé-et-le-plus-faible-quels-fonds-ont-lécart-type-le-plus-élevé-et-le-plus-faible-quelles-séries-semblent-les-plus-et-les-moins-distribués-normalement" id="toc-calculer-les-statistiques-descriptives-univariées-moyenne-variance-écart-type-asymétrie-kurtosis-pour-chaque-fonds-et-commenter-les-résultats.-quels-fonds-ont-le-rendement-moyen-le-plus-élevé-et-le-plus-faible-quels-fonds-ont-lécart-type-le-plus-élevé-et-le-plus-faible-quelles-séries-semblent-les-plus-et-les-moins-distribués-normalement" class="nav-link" data-scroll-target="#calculer-les-statistiques-descriptives-univariées-moyenne-variance-écart-type-asymétrie-kurtosis-pour-chaque-fonds-et-commenter-les-résultats.-quels-fonds-ont-le-rendement-moyen-le-plus-élevé-et-le-plus-faible-quels-fonds-ont-lécart-type-le-plus-élevé-et-le-plus-faible-quelles-séries-semblent-les-plus-et-les-moins-distribués-normalement">5. Calculer les statistiques descriptives univariées (moyenne, variance, écart-type, asymétrie, kurtosis) pour chaque fonds et commenter les résultats. Quels fonds ont le rendement moyen le plus élevé et le plus faible ? Quels fonds ont l’écart type le plus élevé et le plus faible ? Quelles séries semblent les plus et les moins distribués normalement ?</a>
  <ul class="collapse">
  <li><a href="#conclusion-3" id="toc-conclusion-3" class="nav-link" data-scroll-target="#conclusion-3">Conclusion</a></li>
  </ul></li>
  <li><a href="#en-utilisant-un-taux-mensuel-sans-risque-égal-à-05-par-mois-ce-qui-correspond-à-un-taux-annuel-composé-en-continu-de-62-calculer-le-ratio-de-sharpe-pour-chaque-actif.-commenter." id="toc-en-utilisant-un-taux-mensuel-sans-risque-égal-à-05-par-mois-ce-qui-correspond-à-un-taux-annuel-composé-en-continu-de-62-calculer-le-ratio-de-sharpe-pour-chaque-actif.-commenter." class="nav-link" data-scroll-target="#en-utilisant-un-taux-mensuel-sans-risque-égal-à-05-par-mois-ce-qui-correspond-à-un-taux-annuel-composé-en-continu-de-62-calculer-le-ratio-de-sharpe-pour-chaque-actif.-commenter.">6. En utilisant un taux mensuel sans risque égal à 0,5% par mois (ce qui correspond à un taux annuel composé en continu de 6,2%), calculer le ratio de Sharpe pour chaque actif. Commenter.</a>
  <ul class="collapse">
  <li><a href="#conclusion-4" id="toc-conclusion-4" class="nav-link" data-scroll-target="#conclusion-4">Conclusion</a></li>
  </ul></li>
  <li><a href="#déterminez-la-matrice-de-variances-covariances-des-rendements-de-vos-neuf-actifs-et-commenter" id="toc-déterminez-la-matrice-de-variances-covariances-des-rendements-de-vos-neuf-actifs-et-commenter" class="nav-link" data-scroll-target="#déterminez-la-matrice-de-variances-covariances-des-rendements-de-vos-neuf-actifs-et-commenter">7. Déterminez la matrice de variances-covariances des rendements de vos neuf actifs et commenter</a>
  <ul class="collapse">
  <li><a href="#conclusion-5" id="toc-conclusion-5" class="nav-link" data-scroll-target="#conclusion-5">Conclusion</a></li>
  </ul></li>
  <li><a href="#calculer-la-matrice-de-corrélation-des-rendements-de-vos-neuf-actifs-et-tracer-cette-matrice-de-corrélation-à-laide-de-la-fonction-corrplot-du-package-corrplot." id="toc-calculer-la-matrice-de-corrélation-des-rendements-de-vos-neuf-actifs-et-tracer-cette-matrice-de-corrélation-à-laide-de-la-fonction-corrplot-du-package-corrplot." class="nav-link" data-scroll-target="#calculer-la-matrice-de-corrélation-des-rendements-de-vos-neuf-actifs-et-tracer-cette-matrice-de-corrélation-à-laide-de-la-fonction-corrplot-du-package-corrplot.">8. Calculer la matrice de corrélation des rendements de vos neuf actifs et tracer cette matrice de corrélation à l’aide de la fonction corrplot du package corrplot.</a></li>
  <li><a href="#quels-actifs-sont-les-plus-fortement-corrélés-quels-sont-les-moins-corrélés-daprès-les-valeurs-de-corrélations-estimées-pensez-vous-que-la-diversification-réduira-le-risque-avec-ces-actifs" id="toc-quels-actifs-sont-les-plus-fortement-corrélés-quels-sont-les-moins-corrélés-daprès-les-valeurs-de-corrélations-estimées-pensez-vous-que-la-diversification-réduira-le-risque-avec-ces-actifs" class="nav-link" data-scroll-target="#quels-actifs-sont-les-plus-fortement-corrélés-quels-sont-les-moins-corrélés-daprès-les-valeurs-de-corrélations-estimées-pensez-vous-que-la-diversification-réduira-le-risque-avec-ces-actifs">9. Quels actifs sont les plus fortement corrélés ? Quels sont les moins corrélés ? D’après les valeurs de corrélations estimées, pensez-vous que la diversification réduira le risque avec ces actifs ?</a>
  <ul class="collapse">
  <li><a href="#conclusion-6" id="toc-conclusion-6" class="nav-link" data-scroll-target="#conclusion-6">Conclusion</a></li>
  </ul></li>
  <li><a href="#a-partir-de-7-mesures-de-performances-ajustées-au-risque-identifier-pour-chacune-delle-le-titre-le-plus-rentable." id="toc-a-partir-de-7-mesures-de-performances-ajustées-au-risque-identifier-pour-chacune-delle-le-titre-le-plus-rentable." class="nav-link" data-scroll-target="#a-partir-de-7-mesures-de-performances-ajustées-au-risque-identifier-pour-chacune-delle-le-titre-le-plus-rentable.">10. A partir de 7 mesures de performances ajustées au risque, identifier pour chacune d’elle, le titre le plus rentable.</a>
  <ul class="collapse">
  <li><a href="#conclusion-7" id="toc-conclusion-7" class="nav-link" data-scroll-target="#conclusion-7">Conclusion</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exercice-2-théorie-moderne-de-portefeuille" id="toc-exercice-2-théorie-moderne-de-portefeuille" class="nav-link" data-scroll-target="#exercice-2-théorie-moderne-de-portefeuille">Exercice 2 : théorie moderne de portefeuille</a>
  <ul>
  <li><a href="#utilisez-les-9-actifs-précédents." id="toc-utilisez-les-9-actifs-précédents." class="nav-link" data-scroll-target="#utilisez-les-9-actifs-précédents.">1. Utilisez les 9 actifs précédents.</a>
  <ul class="collapse">
  <li><a href="#a.-calculez-le-rendement-du-portefeuille-équipondéré-composé-des-9-fonds-puis-en-déduire-son-écart-type" id="toc-a.-calculez-le-rendement-du-portefeuille-équipondéré-composé-des-9-fonds-puis-en-déduire-son-écart-type" class="nav-link" data-scroll-target="#a.-calculez-le-rendement-du-portefeuille-équipondéré-composé-des-9-fonds-puis-en-déduire-son-écart-type">a. Calculez le rendement du portefeuille équipondéré composé des 9 fonds, puis en déduire son écart type</a></li>
  <li><a href="#b.-quelles-sont-les-propriétés-financières-de-cette-série-de-rendement-obtenue" id="toc-b.-quelles-sont-les-propriétés-financières-de-cette-série-de-rendement-obtenue" class="nav-link" data-scroll-target="#b.-quelles-sont-les-propriétés-financières-de-cette-série-de-rendement-obtenue">b. Quelles sont les propriétés financières de cette série de rendement obtenue ?</a></li>
  <li><a href="#c.-dans-un-plan-moyenne-variance-représentez-les-9-séries." id="toc-c.-dans-un-plan-moyenne-variance-représentez-les-9-séries." class="nav-link" data-scroll-target="#c.-dans-un-plan-moyenne-variance-représentez-les-9-séries.">c.&nbsp;Dans un plan moyenne-variance, représentez les 9 séries.</a></li>
  <li><a href="#d.-déduisez-en-les-titres-inefficients." id="toc-d.-déduisez-en-les-titres-inefficients." class="nav-link" data-scroll-target="#d.-déduisez-en-les-titres-inefficients.">d.&nbsp;Déduisez-en les titres inefficients.</a></li>
  </ul></li>
  <li><a href="#considérez-dans-la-suite-les-trois-premiers-fonds-notamment-les-séries-amundi-cpr-climate-action-i-mainfirst-global-equities-x-et-the-andersons-ande." id="toc-considérez-dans-la-suite-les-trois-premiers-fonds-notamment-les-séries-amundi-cpr-climate-action-i-mainfirst-global-equities-x-et-the-andersons-ande." class="nav-link" data-scroll-target="#considérez-dans-la-suite-les-trois-premiers-fonds-notamment-les-séries-amundi-cpr-climate-action-i-mainfirst-global-equities-x-et-the-andersons-ande.">2. Considérez dans la suite les trois premiers fonds notamment les séries Amundi CPR Climate Action I, MainFirst Global Equities X et The Andersons : (ANDE).</a>
  <ul class="collapse">
  <li><a href="#a.-tracez-la-frontière-efficiente-à-partir-de-toutes-les-combinaisons-possibles-de-ces-trois-titres." id="toc-a.-tracez-la-frontière-efficiente-à-partir-de-toutes-les-combinaisons-possibles-de-ces-trois-titres." class="nav-link" data-scroll-target="#a.-tracez-la-frontière-efficiente-à-partir-de-toutes-les-combinaisons-possibles-de-ces-trois-titres.">a. Tracez la frontière efficiente à partir de toutes les combinaisons possibles de ces trois titres.</a></li>
  <li><a href="#b.-déterminez-le-portefeuille-de-variance-minimale-et-calculer-le-rendement-attendu-et-lécart-type-de-ce-portefeuille.-y-a-t-il-des-pondérations-négatives-dans-le-portefeuille-de-variance-minimale" id="toc-b.-déterminez-le-portefeuille-de-variance-minimale-et-calculer-le-rendement-attendu-et-lécart-type-de-ce-portefeuille.-y-a-t-il-des-pondérations-négatives-dans-le-portefeuille-de-variance-minimale" class="nav-link" data-scroll-target="#b.-déterminez-le-portefeuille-de-variance-minimale-et-calculer-le-rendement-attendu-et-lécart-type-de-ce-portefeuille.-y-a-t-il-des-pondérations-négatives-dans-le-portefeuille-de-variance-minimale">b. Déterminez le portefeuille de variance minimale et calculer le rendement attendu et l’écart-type de ce portefeuille. Y a-t-il des pondérations négatives dans le portefeuille de variance minimale ?</a></li>
  <li><a href="#c.-en-prenant-pour-rendement-de-lactif-sans-risque-𝑟𝑓-25-déterminez-le-portefeuille-tangent." id="toc-c.-en-prenant-pour-rendement-de-lactif-sans-risque-𝑟𝑓-25-déterminez-le-portefeuille-tangent." class="nav-link" data-scroll-target="#c.-en-prenant-pour-rendement-de-lactif-sans-risque-𝑟𝑓-25-déterminez-le-portefeuille-tangent.">c.&nbsp;En prenant pour rendement de l’actif sans risque 𝑟𝑓 = 2,5%, déterminez le portefeuille tangent.</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div style="page-break-after: always;"></div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Pour ce projet, nous nous intéresserons à 9 fonds d’investissement socialement responsable (ISR) suivants, disponibles sur le site Yahoo Finance.</p>
<ol type="1">
<li><p><strong>Amundi CPR Climate Action I</strong>: Ce fonds d’investissement est géré par une équipe expérimentée chez Amundi, l’un des leaders mondiaux de la gestion d’actifs. Le fonds Amundi CPR Climate Action I se concentre sur les investissements durables et responsables, notamment dans des entreprises qui contribuent activement à la lutte contre le changement climatique et à la promotion d’une économie plus verte.</p></li>
<li><p><strong>MainFirst Global Equities X</strong>: Géré par MainFirst, une société de gestion d’actifs reconnue, ce fonds offre une exposition diversifiée aux marchés mondiaux des actions. MainFirst Global Equities X vise à tirer parti des opportunités d’investissement à l’échelle mondiale, en mettant l’accent sur la sélection rigoureuse des actions offrant un potentiel de croissance durable à long terme.</p></li>
<li><p><strong>The Andersons : (ANDE)</strong>: The Andersons est une société diversifiée bien établie, engagée dans plusieurs secteurs d’activité, y compris l’agriculture, l’ingénierie et le commerce. Son ticker symbol (ANDE) indique sa cotation en bourse et son rôle important dans l’économie américaine.</p></li>
<li><p><strong>Carmignac Emergents</strong>: Ce fonds, géré par Carmignac Gestion, se concentre sur les marchés émergents, offrant aux investisseurs une opportunité de diversification géographique et un potentiel de croissance supérieur. Carmignac Emergents vise à identifier les entreprises prometteuses dans les économies en développement et à générer des rendements attractifs à long terme.</p></li>
<li><p><strong>Pluvalca Sustainable Opportunities</strong>: Géré par Pluvalca Investissement, ce fonds met l’accent sur les opportunités d’investissement durable et responsable. Pluvalca Sustainable Opportunities cherche à investir dans des entreprises qui intègrent des critères environnementaux, sociaux et de gouvernance (ESG) dans leur modèle d’affaires, tout en offrant un potentiel de croissance attrayant.</p></li>
<li><p><strong>Fidelity Sustainable Water &amp; Waste R Acc</strong>: Ce fonds, géré par Fidelity Investments, se concentre sur les investissements dans des entreprises liées à la gestion de l’eau et des déchets, avec un accent particulier sur la durabilité et l’impact environnemental. Fidelity Sustainable Water &amp; Waste R Acc vise à générer des rendements solides tout en contribuant à des objectifs environnementaux et sociaux positifs.</p></li>
<li><p><strong>Epsens EdR Tricolore Rendement</strong>: Géré par Edmond de Rothschild Asset Management, ce fonds vise à générer des rendements attrayants en investissant principalement dans des actions françaises. Epsens EdR Tricolore Rendement bénéficie de l’expertise et de l’expérience de l’équipe de gestion d’actifs d’Edmond de Rothschild pour identifier les opportunités d’investissement sur les marchés français.</p></li>
<li><p><strong>Thematics Water R/A USD</strong>: Ce fonds, géré par Thematics Asset Management, se concentre sur les investissements dans des entreprises liées au secteur de l’eau. Thematics Water R/A USD offre aux investisseurs une exposition à un thème d’investissement spécifique, tout en cherchant à capturer les opportunités de croissance dans un secteur essentiel à long terme.</p></li>
<li><p><strong>AIS Mandarine Global Transition</strong>: Géré par Mandarine Gestion, ce fonds vise à investir dans des entreprises ou des projets qui contribuent à la transition vers une économie plus durable. AIS Mandarine Global Transition cherche à identifier les leaders du marché dans des secteurs clés de la transition énergétique et environnementale, offrant ainsi aux investisseurs une exposition à long terme à des thèmes d’investissement stratégiques.</p></li>
</ol>
<div style="page-break-after: always;"></div>
</section>
<section id="exercice-1-calcul-de-rendements-statistiques-usuelles-et-performance-des-titres" class="level2">
<h2 class="anchored" data-anchor-id="exercice-1-calcul-de-rendements-statistiques-usuelles-et-performance-des-titres">Exercice 1 : Calcul de rendements, statistiques usuelles et performance des titres</h2>
<section id="calculer-et-représenter-les-prix-et-les-rendements-de-chacun-des-fonds-en-fonction-du-temps.-commentez-les-résultats." class="level3">
<h3 class="anchored" data-anchor-id="calculer-et-représenter-les-prix-et-les-rendements-de-chacun-des-fonds-en-fonction-du-temps.-commentez-les-résultats.">1. Calculer et représenter les prix et les rendements de chacun des fonds en fonction du temps. Commentez les résultats.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chargement des packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xts)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(TTR)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Titres Amundi CPR Climate Action I</strong> Les résultats pour le fonds “Amundi CPR Climate Action I” montrent une évolution intéressante des prix et des rendements tout au long de l’année 2023.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import des données</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>X0P0001IYTY_F <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"./Databases/0P0001IYTY.F.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> X0P0001IYTY_F</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir les colonnes Open et Close en type numérique</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> data1 <span class="sc">%&gt;%</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Open =</span> <span class="fu">as.numeric</span>(Open),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">Close =</span> <span class="fu">as.numeric</span>(Close))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Conversion de la colonne de date en format Date</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>data1<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(data1<span class="sc">$</span>Date)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Remplacement des valeurs null ou manquantes par NA</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>data1[<span class="fu">is.na</span>(data1)] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Supprimer les lignes contenant des valeurs manquantes</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(data1)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les rendements pour l'ensemble des données</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> data1 <span class="sc">%&gt;%</span> </span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Date) <span class="sc">%&gt;%</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Rendement =</span> Close <span class="sc">/</span> <span class="fu">lag</span>(Close) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> data1 <span class="sc">%&gt;%</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Rendement =</span> <span class="fu">replace_na</span>(Rendement, <span class="dv">0</span>))</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Représentation des prix</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data1, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Close)) <span class="sc">+</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Évolution des prix des titres Amundi CPR Climate Action I"</span>,</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Prix de clôture"</span>) <span class="sc">+</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les prix moyens semblent fluctuer au fil des mois, avec une tendance générale à la hausse au début de l’année, suivie d’une période de fluctuation, de légère baisse au début du quatrième semestre, et finalement d’une forte hausse vers la fin de l’année. En particulier, une augmentation notable des prix est observée en mars, suivie d’une légère baisse en avril et mai, puis une tendance à la hausse en juin et juillet. Ensuite, nous constatons une certaine volatilité avec des variations jusqu’à la fin de l’année.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Représentation des rendements</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data1, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Rendement)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Évolution des rendements des titres Amundi CPR Climate Action I"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Rendement"</span>) <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les rendements moyens montrent également une variabilité mensuelle. Nous observons des rendements positifs en janvier, février, mai, juin et novembre, avec des performances particulièrement fortes en novembre. Cependant, il y a aussi des mois avec des rendements négatifs, tels que mars, septembre et octobre.</p>
<p>En général, ces résultats suggèrent une certaine volatilité dans les performances du fonds “Amundi CPR Climate Action I” au cours de l’année 2023. Il serait intéressant de creuser davantage pour comprendre les facteurs sous-jacents qui ont influencé ces fluctuations de prix et de rendements, ainsi que d’analyser la performance relative par rapport à d’autres fonds d’investissement socialement responsables.</p>
<p><strong>Titres MainFirst Global Equities X</strong> Les résultats pour le fonds MainFirst Global Equities X montrent une évolution des prix moyens et des rendements moyens au fil du temps pour chaque mois de l’année 2023.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>On observe une variation des prix moyens du fonds tout au long de l’année 2023. Les prix moyens semblent fluctuer, avec des hauts et des bas d’un mois à l’autre. Par exemple, les prix moyens atteignent leur plus bas niveau en mars (126) et leur plus haut niveau en juillet (139), avec des variations entre ces extrêmes au cours des autres mois.</p>
<p>Les rendements moyens du fonds présentent également des variations mensuelles. Certains mois affichent des rendements positifs, tandis que d’autres affichent des rendements négatifs. Par exemple, les rendements moyens sont positifs en janvier, juin, juillet et novembre, tandis qu’ils sont négatifs en février, avril, août et septembre.</p>
<p>Bien que les prix et les rendements fluctuent d’un mois à l’autre, il semble y avoir certaines tendances générales au fil de l’année. Par exemple, les prix semblent augmenter progressivement au cours des premiers mois de l’année, avec un pic en juillet, avant de baisser légèrement vers la fin de l’année. Les rendements moyens semblent également suivre des tendances similaires, bien qu’avec plus de variations d’un mois à l’autre.</p>
<p>Il serait intéressant d’analyser les facteurs externes qui ont pu influencer les performances du fonds au cours de cette période, tels que les conditions économiques mondiales, les événements politiques, ou les tendances du marché financier. Ces facteurs pourraient expliquer les variations observées dans les prix et les rendements du fonds.</p>
<p>En résumé, l’analyse des prix moyens et des rendements moyens du fonds MainFirst Global Equities X pour l’année 2023 montre une évolution fluctuante mais présentant certaines tendances générales au fil du temps. Une analyse plus approfondie des facteurs influents pourrait fournir des insights supplémentaires sur les performances du fonds.</p>
<p><strong>Titres The Andersons : (ANDE)</strong> Les données fournies présentent les moyennes mensuelles des prix et des rendements pour le fonds The Andersons (ANDE) sur l’année 2023.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les prix moyens semblent avoir une tendance générale à la hausse au cours de l’année, avec quelques fluctuations mensuelles. Les prix ont augmenté progressivement jusqu’en juin, puis ont diminué légèrement en juillet et août, pour ensuite augmenter à nouveau jusqu’en décembre, atteignant un niveau plus élevé à la fin de l’année.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les rendements moyens présentent une variabilité mensuelle plus prononcée. On observe des fluctuations positives et négatives tout au long de l’année, indiquant une volatilité dans les performances du fonds. Cependant, la tendance globale semble être légèrement positive, avec des rendements positifs plus fréquents que les rendements négatifs.</p>
<p>Il serait intéressant d’examiner s’il existe une corrélation entre les mouvements de prix et les rendements pour ce fonds. Par exemple, des hausses de prix sont-elles généralement suivies de rendements positifs, et vice versa ? Cette analyse pourrait aider à mieux comprendre la dynamique de performance du fonds.</p>
<p>En résumé, les données indiquent une évolution positive des prix moyens au fil du temps, avec des rendements moyens fluctuant mais légèrement positifs sur l’ensemble de l’année. Cependant, une analyse plus approfondie serait nécessaire pour évaluer pleinement les performances du fonds The Andersons (ANDE) et comprendre les facteurs qui influencent ses prix et rendements.</p>
<p><strong>Titres Carmignac Emergents</strong> Les résultats montrent l’évolution des prix moyens et des rendements moyens du fonds Carmignac Emergents au cours de l’année 2023.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les prix moyens semblent fluctuer légèrement au cours de l’année, avec des variations relativement modérées. Ils ont atteint leur point le plus bas en mai 2023 à environ 144, puis ont légèrement augmenté pour se situer autour de 152 à la fin de l’année.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les rendements moyens du fonds Carmignac Emergents montrent une certaine volatilité au cours de l’année. Ils varient autour de zéro pour la plupart des mois, mais ils présentent quelques fluctuations positives et négatives. En général, les rendements semblent être assez faibles, avec quelques mois de rendements légèrement positifs et d’autres légèrement négatifs.</p>
<p>Globalement, les prix et les rendements du fonds Carmignac Emergents semblent relativement stables au cours de l’année, avec quelques fluctuations modérées mais sans tendance forte à la hausse ou à la baisse.</p>
<p>Ces observations peuvent être utilisées pour évaluer la performance du fonds Carmignac Emergents au cours de l’année 2023 et peuvent aider les investisseurs à prendre des décisions éclairées concernant leur portefeuille d’investissement.</p>
<p><strong>Titres Pluvalca Sustainable Opportunities</strong> Les résultats pour le fonds Pluvalca Sustainable Opportunities montrent une variation des prix et des rendements au fil du temps.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les prix moyens semblent avoir fluctué au cours de l’année 2023, avec une tendance générale à la baisse jusqu’au mois d’octobre, suivi d’une légère remontée vers la fin de l’année. Cette évolution peut être influencée par divers facteurs économiques et commerciaux qui ont impacté la valeur des actifs détenus par le fonds.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Il est intéressant de noter que les prix et les rendements semblent suivre des tendances saisonnières, avec des mouvements spécifiques observés à différents moments de l’année. Par exemple, une tendance à la baisse des prix et des rendements est observée vers la fin de l’année, tandis qu’une tendance à la hausse est observée vers le début de l’année.</p>
<p>En résumé, l’analyse des prix et des rendements du fonds Pluvalca Sustainable Opportunities indique une certaine volatilité au cours de l’année 2023, avec des fluctuations influencées par divers facteurs économiques et commerciaux.</p>
<p><strong>Titres Fidelity Sustainable Water &amp; Waste R Acc</strong> Les données fournies représentent la moyenne mensuelle des prix et des rendements pour le fonds Fidelity Sustainable Water &amp; Waste R Acc sur l’année 2023.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>On observe une fluctuation des prix moyens mensuels tout au long de l’année, avec des variations allant de 93,1 à 102. Ces fluctuations peuvent être dues à divers facteurs tels que l’offre et la demande sur le marché, les performances de l’entreprise sous-jacente, ainsi que les conditions macroéconomiques et géopolitiques.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les rendements moyens mensuels varient également tout au long de l’année, oscillant entre -0,25% et 0,38%. Ces variations reflètent les performances du fonds d’un mois à l’autre. Les rendements positifs indiquent une croissance du capital investi, tandis que les rendements négatifs indiquent une diminution. En regardant les données dans leur ensemble, il semble y avoir une tendance à la hausse des prix et des rendements moyens vers la fin de l’année. Cela suggère que le fonds a peut-être affiché de meilleures performances au cours des derniers mois de l’année.</p>
<p>Pour une analyse plus approfondie, il serait intéressant de comparer ces résultats avec ceux des autres fonds ISR étudiés, ainsi qu’avec des indices de référence du secteur. Cela pourrait fournir des insights supplémentaires sur les performances relatives du fonds par rapport à ses pairs et au marché dans son ensemble.</p>
<p>En résumé, ces données fournissent une vue d’ensemble des performances mensuelles du fonds Fidelity Sustainable Water &amp; Waste R Acc en 2023, mais une analyse plus approfondie est nécessaire pour comprendre pleinement son comportement et son positionnement par rapport à d’autres investissements.</p>
<p><strong>Titres Epsens EdR Tricolore Rendement</strong> Les données fournies représentent la moyenne mensuelle des prix et des rendements pour le fonds “Epsens EdR Tricolore Rendement” sur l’année 2023.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les prix moyens semblent fluctuer légèrement au cours de l’année, suivi d’une hausse, avec des variations relativement faibles. On observe une légère baisse vers la fin de l’année, avec un prix moyen en décembre légèrement plus élevé que le début de l’année. Cela peut indiquer une stabilité globale des prix, avec quelques variations mineures.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les rendements moyens varient également au fil des mois, oscillant autour de zéro. Cependant, on peut observer une certaine volatilité des rendements, avec des variations positives et négatives au cours de l’année. En particulier, il y a une augmentation notable des rendements en novembre, suivie d’une légère baisse en décembre.</p>
<p>La stabilité des prix moyens suggère une certaine régularité dans la performance du fonds tout au long de l’année. Cependant, la volatilité des rendements indique une certaine variabilité dans la performance mensuelle du fonds. Il peut être intéressant d’approfondir l’analyse pour comprendre les facteurs sous-jacents à ces variations de rendements.</p>
<p>En résumé, les données montrent une certaine stabilité des prix moyens avec une variabilité des rendements mensuels pour le fonds “Epsens EdR Tricolore Rendement” en 2023. Une analyse plus approfondie pourrait aider à mieux comprendre les performances et les tendances de ce fonds au fil du temps.</p>
<p><strong>Titres Thematics Water R/A USD</strong> Les résultats pour data8_mois montrent la moyenne mensuelle des prix et des rendements pour le fonds Thematics Water R/A USD pour l’année 2023.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La moyenne mensuelle des prix oscille autour de 24,4 USD à 26,3 USD au cours de l’année. On observe une légère augmentation du prix moyen au début de l’année, suivie de fluctuations légères mais relativement stables tout au long de l’année.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Les rendements moyens varient entre -0,22% et 0,36% par mois. On observe une certaine volatilité dans les rendements, avec des mois positifs et négatifs alternant tout au long de l’année. Le rendement le plus élevé est observé en novembre, tandis que le rendement le plus bas est enregistré en septembre.</p>
<p>Les tendances mensuelles des prix et des rendements peuvent être utilisées pour évaluer la performance du fonds au fil du temps. Par exemple, une tendance à la hausse des prix et des rendements peut indiquer une performance solide du fonds, tandis qu’une volatilité accrue peut nécessiter une analyse plus approfondie pour comprendre les facteurs sous-jacents.</p>
<p>En résumé, l’analyse des moyennes mensuelles des prix et des rendements fournit un aperçu de la performance du fonds Thematics Water R/A USD en 2023, en mettant en évidence les variations mensuelles et la volatilité des rendements. Ces informations peuvent être utiles pour les investisseurs dans leur processus de prise de décision.</p>
<p><strong>Titres AIS Mandarine Global Transition</strong> Les résultats montrent la moyenne mensuelle des prix et des rendements du fonds AIS Mandarine Global Transition pour chaque mois de l’année 2023.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En examinant ces résultats, on peut observer des variations dans les prix moyens et les rendements moyens tout au long de l’année 2023 pour le fonds AIS Mandarine Global Transition. Par exemple, on remarque une baisse des prix moyens en mars et en avril, suivie d’une légère augmentation en mai et juin. De même, les rendements moyens varient également mois par mois, reflétant les fluctuations du marché et les performances du fonds.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion</h4>
<p>Il semble y avoir une certaine cohérence dans les observations faites pour chaque fonds, malgré les différences dans les détails spécifiques. Pour la plupart des fonds, on observe des variations mensuelles des prix et des rendements, indiquant une certaine volatilité tout au long de l’année 2023. Par exemple, pour le fonds “Amundi CPR Climate Action I”, nous avons observé une tendance générale à la hausse des prix au début de l’année, suivie d’une période de fluctuation et de légère baisse vers la fin de l’année. Les rendements ont également varié, avec des performances positives et négatives tout au long de l’année, indiquant une certaine volatilité dans les performances du fonds.</p>
<p>De même, pour d’autres fonds comme “MainFirst Global Equities X” et “The Andersons (ANDE)”, nous avons observé des tendances similaires de fluctuation des prix et des rendements, avec des variations mensuelles reflétant probablement les conditions économiques et commerciales changeantes. En résumé, ces observations soulignent l’importance d’une analyse approfondie des performances des fonds d’investissement, en examinant à la fois les prix moyens et les rendements moyens pour mieux comprendre leur comportement au fil du temps.</p>
</section>
</section>
<section id="quelles-sont-les-propriétés-financières-de-chacune-des-séries" class="level3">
<h3 class="anchored" data-anchor-id="quelles-sont-les-propriétés-financières-de-chacune-des-séries">2. Quelles sont les propriétés financières de chacune des séries ?</h3>
</section>
<section id="y-a-t-il-des-retours-à-la-moyenne-pouvez-vous-identifier-des-événements-dactualité-qui-pourraient-expliquer-des-valeurs-inhabituelles" class="level3">
<h3 class="anchored" data-anchor-id="y-a-t-il-des-retours-à-la-moyenne-pouvez-vous-identifier-des-événements-dactualité-qui-pourraient-expliquer-des-valeurs-inhabituelles">3. Y a-t-il des retours à la moyenne ? Pouvez-vous identifier des événements d’actualité qui pourraient expliquer des valeurs inhabituelles ?</h3>
<p><strong>Amundi CPR Climate Action I</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile sur 7 jours</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>sma_7 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data1<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">7</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile 30 jours</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>sma_30 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data1<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Identifier les croisements entre les moyennes mobiles</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sma_7 <span class="sc">&gt;</span> sma_30, <span class="st">"Au-dessus"</span>, <span class="st">"En dessous"</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, crossings[<span class="sc">-</span><span class="fu">length</span>(crossings)])  <span class="co"># décaler le vecteur d'une période</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un data frame avec les données et les croisements</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>data1_with_crossings <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Date =</span> <span class="fu">index</span>(data1),</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">Close =</span> data1<span class="sc">$</span>Close,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">SMA_7 =</span> sma_7,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">SMA_30 =</span> sma_30,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">Crossing =</span> crossings)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les observations avec des croisements</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>crossing_points <span class="ot">&lt;-</span> data1_with_crossings[<span class="sc">!</span><span class="fu">is.na</span>(data1_with_crossings<span class="sc">$</span>Crossing), ]</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(crossing_points)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Date   Close    SMA_7   SMA_30   Crossing
31    31 1351.16 1344.769 1313.286  Au-dessus
32    32 1356.61 1347.577 1316.516  Au-dessus
33    33 1350.45 1347.609 1319.149  Au-dessus
34    34 1348.02 1348.240 1321.466  Au-dessus
35    35 1345.42 1349.207 1323.340  Au-dessus
36    36 1324.72 1346.613 1324.828  Au-dessus
37    37 1326.91 1343.327 1326.198  Au-dessus
38    38 1329.02 1340.164 1327.327  Au-dessus
39    39 1327.68 1336.031 1328.278  Au-dessus
40    40 1326.29 1332.580 1329.091  Au-dessus
41    41 1315.33 1327.910 1329.380  Au-dessus
42    42 1324.34 1324.899 1330.315 En dessous
43    43 1340.87 1327.206 1332.152 En dessous
44    44 1334.03 1328.223 1333.400 En dessous
45    45 1324.95 1327.641 1334.023 En dessous
46    46 1328.80 1327.801 1334.667 En dessous
47    47 1310.38 1325.529 1334.636 En dessous
48    48 1260.21 1317.654 1332.482 En dessous
49    49 1273.10 1310.334 1330.448 En dessous
50    50 1273.32 1300.684 1328.980 En dessous
51    51 1280.85 1293.087 1327.403 En dessous
52    52 1267.98 1284.949 1325.340 En dessous
53    53 1270.95 1276.684 1323.022 En dessous
54    54 1278.38 1272.113 1321.066 En dessous
55    55 1264.89 1272.781 1318.664 En dessous
56    56 1261.25 1271.089 1315.698 En dessous
57    57 1270.37 1270.667 1313.257 En dessous
58    58 1273.16 1269.569 1311.074 En dessous
59    59 1266.93 1269.419 1308.543 En dessous
60    60 1282.74 1271.103 1306.304 En dessous
61    61 1302.63 1274.567 1304.686 En dessous
62    62 1301.21 1279.756 1302.839 En dessous
63    63 1289.11 1283.736 1300.795 En dessous
64    64 1288.90 1286.383 1298.824 En dessous
65    65 1296.47 1289.713 1297.192 En dessous
66    66 1294.55 1293.659 1296.187 En dessous
67    67 1287.50 1294.339 1294.873 En dessous
68    68 1292.16 1292.843 1293.644 En dessous
69    69 1293.77 1291.780 1292.514 En dessous
70    70 1304.53 1293.983 1291.789 En dessous
71    71 1304.29 1296.181 1291.421  Au-dessus
72    72 1305.50 1297.471 1290.793  Au-dessus
73    73 1297.36 1297.873 1289.342  Au-dessus
74    74 1297.60 1299.316 1288.128  Au-dessus
75    75 1291.57 1299.231 1287.015  Au-dessus
76    76 1284.68 1297.933 1285.545  Au-dessus
77    77 1274.46 1293.637 1284.347  Au-dessus
78    78 1288.84 1291.430 1285.302  Au-dessus
79    79 1296.75 1290.180 1286.090  Au-dessus
80    80 1284.59 1288.356 1286.466  Au-dessus
81    81 1275.71 1285.229 1286.294  Au-dessus
82    82 1272.02 1282.436 1286.429 En dessous
83    83 1291.33 1283.386 1287.108 En dessous
84    84 1294.18 1286.203 1287.635 En dessous
85    85 1296.90 1287.354 1288.702 En dessous
86    86 1297.19 1287.417 1289.900 En dessous
87    87 1295.41 1288.963 1290.735 En dessous
88    88 1303.13 1292.880 1291.734 En dessous
89    89 1306.77 1297.844 1293.062  Au-dessus
90    90 1297.77 1298.764 1293.563  Au-dessus
91    91 1323.90 1303.010 1294.272  Au-dessus
92    92 1324.72 1306.984 1295.055  Au-dessus
93    93 1325.05 1310.964 1296.253  Au-dessus
94    94 1315.59 1313.847 1297.143  Au-dessus
95    95 1303.62 1313.917 1297.381  Au-dessus
96    96 1310.48 1314.447 1297.912  Au-dessus
97    97 1332.96 1319.474 1299.428  Au-dessus
98    98 1328.59 1320.144 1300.642  Au-dessus
99    99 1325.40 1320.241 1301.696  Au-dessus
100  100 1332.45 1321.299 1302.627  Au-dessus
101  101 1349.06 1326.080 1304.119  Au-dessus
102  102 1354.04 1333.283 1305.737  Au-dessus
103  103 1344.02 1338.074 1307.293  Au-dessus
104  104 1349.60 1340.451 1309.026  Au-dessus
105  105 1360.55 1345.017 1311.325  Au-dessus
106  106 1366.19 1350.844 1314.042  Au-dessus
107  107 1365.43 1355.556 1317.075  Au-dessus
108  108 1369.37 1358.457 1319.759  Au-dessus
109  109 1365.20 1360.051 1322.041  Au-dessus
110  110 1359.59 1362.276 1324.541  Au-dessus
111  111 1351.97 1362.614 1327.083  Au-dessus
112  112 1341.28 1359.861 1329.391  Au-dessus
113  113 1336.01 1355.550 1330.881  Au-dessus
114  114 1343.22 1352.377 1332.515  Au-dessus
115  115 1350.14 1349.630 1334.290  Au-dessus
116  116 1354.51 1348.103 1336.201  Au-dessus
117  117 1365.44 1348.939 1338.535  Au-dessus
118  118 1365.94 1350.934 1340.629  Au-dessus
119  119 1365.19 1354.350 1342.576  Au-dessus
120  120 1362.96 1358.200 1344.749  Au-dessus
121  121 1345.44 1358.517 1345.467  Au-dessus
122  122 1336.99 1356.639 1345.876  Au-dessus
123  123 1338.14 1354.300 1346.312  Au-dessus
124  124 1346.57 1351.604 1347.345  Au-dessus
125  125 1344.54 1348.547 1348.709  Au-dessus
126  126 1350.16 1346.400 1350.032 En dessous
127  127 1345.27 1343.873 1350.442 En dessous
128  128 1345.21 1343.840 1350.996 En dessous
129  129 1354.13 1346.289 1351.954 En dessous
130  130 1364.14 1350.003 1353.010 En dessous
131  131 1364.24 1352.527 1353.516 En dessous
132  132 1365.80 1355.564 1353.908 En dessous
133  133 1373.43 1358.889 1354.888  Au-dessus
134  134 1380.00 1363.850 1355.902  Au-dessus
135  135 1374.01 1367.964 1356.350  Au-dessus
136  136 1374.69 1370.901 1356.634  Au-dessus
137  137 1376.22 1372.627 1356.993  Au-dessus
138  138 1381.23 1375.054 1357.389  Au-dessus
139  139 1381.21 1377.256 1357.922  Au-dessus
140  140 1363.49 1375.836 1358.052  Au-dessus
141  141 1353.87 1372.103 1358.116  Au-dessus
142  142 1342.19 1367.557 1358.146  Au-dessus
143  143 1348.71 1363.846 1358.569  Au-dessus
144  144 1342.73 1359.061 1358.553  Au-dessus
145  145 1334.32 1352.360 1358.026  Au-dessus
146  146 1330.42 1345.104 1357.223 En dessous
147  147 1330.11 1340.336 1356.045 En dessous
148  148 1326.39 1336.410 1354.727 En dessous
149  149 1320.75 1333.347 1353.245 En dessous
150  150 1320.59 1329.330 1351.833 En dessous
151  151 1327.69 1327.181 1351.241 En dessous
152  152 1334.15 1327.157 1351.147 En dessous
153  153 1345.67 1329.336 1351.398 En dessous
154  154 1332.79 1329.719 1350.938 En dessous
155  155 1340.59 1331.747 1350.807 En dessous
156  156 1349.85 1335.904 1350.796 En dessous
157  157 1362.18 1341.846 1351.360 En dessous
158  158 1357.47 1346.100 1351.769 En dessous
159  159 1363.45 1350.286 1352.079 En dessous
160  160 1370.38 1353.816 1352.287 En dessous
161  161 1371.52 1359.349 1352.530  Au-dessus
162  162 1373.57 1364.060 1352.789  Au-dessus
163  163 1367.91 1366.640 1352.605  Au-dessus
164  164 1365.10 1367.057 1352.108  Au-dessus
165  165 1361.09 1367.574 1351.678  Au-dessus
166  166 1366.11 1367.954 1351.392  Au-dessus
167  167 1365.56 1367.266 1351.036  Au-dessus
168  168 1360.79 1365.733 1350.355  Au-dessus
169  169 1373.75 1365.759 1350.106  Au-dessus
170  170 1367.73 1365.733 1350.248  Au-dessus
171  171 1361.63 1365.237 1350.506  Au-dessus
172  172 1353.70 1364.181 1350.890  Au-dessus
173  173 1338.53 1360.241 1350.551  Au-dessus
174  174 1335.17 1355.900 1350.299  Au-dessus
175  175 1341.92 1353.204 1350.552  Au-dessus
176  176 1325.18 1346.266 1350.377  Au-dessus
177  177 1329.40 1340.790 1350.354 En dessous
178  178 1329.60 1336.214 1350.461 En dessous
179  179 1325.52 1332.189 1350.620 En dessous
180  180 1327.11 1330.557 1350.837 En dessous
181  181 1308.70 1326.776 1350.204 En dessous
182  182 1312.88 1322.627 1349.495 En dessous
183  183 1324.07 1322.469 1348.775 En dessous
184  184 1327.05 1322.133 1348.584 En dessous
185  185 1336.21 1323.077 1348.438 En dessous
186  186 1337.98 1324.857 1348.042 En dessous
187  187 1340.08 1326.710 1347.305 En dessous
188  188 1331.21 1329.926 1346.430 En dessous
189  189 1334.05 1332.950 1345.450 En dessous
190  190 1333.43 1334.287 1344.218 En dessous
191  191 1318.31 1333.039 1342.445 En dessous
192  192 1304.74 1328.543 1340.150 En dessous
193  193 1285.84 1321.094 1337.415 En dessous
194  194 1279.32 1312.414 1334.555 En dessous
195  195 1289.55 1306.463 1332.171 En dessous
196  196 1267.55 1296.963 1328.885 En dessous
197  197 1271.75 1288.151 1325.758 En dessous
198  198 1302.45 1285.886 1323.814 En dessous
199  199 1317.32 1287.683 1321.933 En dessous
200  200 1320.82 1292.680 1320.369 En dessous
201  201 1318.33 1298.253 1318.926 En dessous
202  202 1320.86 1302.726 1317.831 En dessous
203  203 1317.94 1309.924 1317.145 En dessous
204  204 1319.11 1316.690 1316.609 En dessous
205  205 1332.24 1320.946 1316.287  Au-dessus
206  206 1343.64 1324.706 1316.902  Au-dessus
207  207 1346.48 1328.371 1317.471  Au-dessus
208  208 1346.47 1332.391 1318.034  Au-dessus
209  209 1352.18 1336.866 1318.922  Au-dessus
210  210 1354.23 1342.050 1319.826  Au-dessus
211  211 1362.27 1348.216 1321.612  Au-dessus
212  212 1359.24 1352.073 1323.157  Au-dessus
213  213 1359.61 1354.354 1324.342  Au-dessus
214  214 1357.30 1355.900 1325.350  Au-dessus
215  215 1355.07 1357.129 1325.979  Au-dessus
216  216 1361.32 1358.434 1326.757  Au-dessus
217  217 1373.71 1361.217 1327.878  Au-dessus
218  218 1388.37 1364.946 1329.783  Au-dessus
219  219 1381.90 1368.183 1331.378  Au-dessus
220  220 1383.99 1371.666 1333.064  Au-dessus
221  221 1387.60 1375.994 1335.373  Au-dessus
222  222 1397.59 1382.069 1338.468  Au-dessus
223  223 1404.02 1388.169 1342.408  Au-dessus
224  224 1406.18 1392.807 1346.636  Au-dessus
225  225 1418.11 1397.056 1350.922  Au-dessus
226  226 1406.36 1400.550 1355.549  Au-dessus
227  227 1410.86 1404.389 1360.186  Au-dessus
228  228 1412.23 1407.907 1363.845  Au-dessus
229  229 1401.22 1408.426 1366.642  Au-dessus
230  230 1408.75 1409.101 1369.573  Au-dessus
231  231 1412.01 1409.934 1372.695  Au-dessus
232  232 1408.71 1408.591 1375.624  Au-dessus
233  233 1410.41 1409.170 1378.706  Au-dessus</code></pre>
</div>
</div>
<p><strong>MainFirst Global Equities X</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile sur 7 jours</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>sma_7 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data2<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">7</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile 30 jours</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>sma_30 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data2<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Identifier les croisements entre les moyennes mobiles</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sma_7 <span class="sc">&gt;</span> sma_30, <span class="st">"Au-dessus"</span>, <span class="st">"En dessous"</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, crossings[<span class="sc">-</span><span class="fu">length</span>(crossings)])  <span class="co"># décaler le vecteur d'une période</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un data frame avec les données et les croisements</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>data2_with_crossings <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Date =</span> <span class="fu">index</span>(data2),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Close =</span> data2<span class="sc">$</span>Close,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_7 =</span> sma_7,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_30 =</span> sma_30,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Crossing =</span> crossings)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les observations avec des croisements</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>crossing_points2 <span class="ot">&lt;-</span> data2_with_crossings[<span class="sc">!</span><span class="fu">is.na</span>(data2_with_crossings<span class="sc">$</span>Crossing), ]</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(crossing_points2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>The Andersons : (ANDE)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile sur 7 jours</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>sma_7 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data3<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">7</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile 30 jours</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>sma_30 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data3<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Identifier les croisements entre les moyennes mobiles</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sma_7 <span class="sc">&gt;</span> sma_30, <span class="st">"Au-dessus"</span>, <span class="st">"En dessous"</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, crossings[<span class="sc">-</span><span class="fu">length</span>(crossings)])  <span class="co"># décaler le vecteur d'une période</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un data frame avec les données et les croisements</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>data3_with_crossings <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Date =</span> <span class="fu">index</span>(data3),</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Close =</span> data3<span class="sc">$</span>Close,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_7 =</span> sma_7,</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_30 =</span> sma_30,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Crossing =</span> crossings)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les observations avec des croisements</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>crossing_points3 <span class="ot">&lt;-</span> data3_with_crossings[<span class="sc">!</span><span class="fu">is.na</span>(data3_with_crossings<span class="sc">$</span>Crossing), ]</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(crossing_points3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Carmignac Emergents</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile sur 7 jours</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>sma_7 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data4<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">7</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile 30 jours</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>sma_30 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data4<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Identifier les croisements entre les moyennes mobiles</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sma_7 <span class="sc">&gt;</span> sma_30, <span class="st">"Au-dessus"</span>, <span class="st">"En dessous"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, crossings[<span class="sc">-</span><span class="fu">length</span>(crossings)])  <span class="co"># décaler le vecteur d'une période</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un data frame avec les données et les croisements</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>data4_with_crossings <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Date =</span> <span class="fu">index</span>(data4),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Close =</span> data4<span class="sc">$</span>Close,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_7 =</span> sma_7,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_30 =</span> sma_30,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Crossing =</span> crossings)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les observations avec des croisements</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>crossing_points4 <span class="ot">&lt;-</span> data4_with_crossings[<span class="sc">!</span><span class="fu">is.na</span>(data4_with_crossings<span class="sc">$</span>Crossing), ]</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(crossing_points4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Pluvalca Sustainable Opportunities</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile sur 7 jours</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>sma_7 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data5<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">7</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile 30 jours</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>sma_30 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data5<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Identifier les croisements entre les moyennes mobiles</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sma_7 <span class="sc">&gt;</span> sma_30, <span class="st">"Au-dessus"</span>, <span class="st">"En dessous"</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, crossings[<span class="sc">-</span><span class="fu">length</span>(crossings)])  <span class="co"># décaler le vecteur d'une période</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un data frame avec les données et les croisements</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>data5_with_crossings <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Date =</span> <span class="fu">index</span>(data5),</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Close =</span> data5<span class="sc">$</span>Close,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_7 =</span> sma_7,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_30 =</span> sma_30,</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Crossing =</span> crossings)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les observations avec des croisements</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>crossing_points5 <span class="ot">&lt;-</span> data5_with_crossings[<span class="sc">!</span><span class="fu">is.na</span>(data5_with_crossings<span class="sc">$</span>Crossing), ]</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(crossing_points5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Fidelity Sustainable Water &amp; Waste R Acc</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile sur 7 jours</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>sma_7 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data6<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">7</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile 30 jours</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>sma_30 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data6<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Identifier les croisements entre les moyennes mobiles</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sma_7 <span class="sc">&gt;</span> sma_30, <span class="st">"Au-dessus"</span>, <span class="st">"En dessous"</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, crossings[<span class="sc">-</span><span class="fu">length</span>(crossings)])  <span class="co"># décaler le vecteur d'une période</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un data frame avec les données et les croisements</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>data6_with_crossings <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Date =</span> <span class="fu">index</span>(data6),</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Close =</span> data6<span class="sc">$</span>Close,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_7 =</span> sma_7,</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_30 =</span> sma_30,</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Crossing =</span> crossings)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les observations avec des croisements</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>crossing_points6 <span class="ot">&lt;-</span> data6_with_crossings[<span class="sc">!</span><span class="fu">is.na</span>(data6_with_crossings<span class="sc">$</span>Crossing), ]</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(crossing_points6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Epsens EdR Tricolore Rendement</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile sur 7 jours</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>sma_7 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data7<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">7</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile 30 jours</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>sma_30 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data7<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Identifier les croisements entre les moyennes mobiles</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sma_7 <span class="sc">&gt;</span> sma_30, <span class="st">"Au-dessus"</span>, <span class="st">"En dessous"</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, crossings[<span class="sc">-</span><span class="fu">length</span>(crossings)])  <span class="co"># décaler le vecteur d'une période</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un data frame avec les données et les croisements</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>data7_with_crossings <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Date =</span> <span class="fu">index</span>(data7),</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Close =</span> data7<span class="sc">$</span>Close,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_7 =</span> sma_7,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_30 =</span> sma_30,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Crossing =</span> crossings)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les observations avec des croisements</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>crossing_points7 <span class="ot">&lt;-</span> data7_with_crossings[<span class="sc">!</span><span class="fu">is.na</span>(data7_with_crossings<span class="sc">$</span>Crossing), ]</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(crossing_points7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Thematics Water R/A USD</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile sur 7 jours</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>sma_7 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data8<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">7</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile 30 jours</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>sma_30 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data8<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Identifier les croisements entre les moyennes mobiles</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sma_7 <span class="sc">&gt;</span> sma_30, <span class="st">"Au-dessus"</span>, <span class="st">"En dessous"</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, crossings[<span class="sc">-</span><span class="fu">length</span>(crossings)])  <span class="co"># décaler le vecteur d'une période</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un data frame avec les données et les croisements</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>data8_with_crossings <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Date =</span> <span class="fu">index</span>(data8),</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Close =</span> data8<span class="sc">$</span>Close,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_7 =</span> sma_7,</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_30 =</span> sma_30,</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Crossing =</span> crossings)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les observations avec des croisements</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>crossing_points8 <span class="ot">&lt;-</span> data8_with_crossings[<span class="sc">!</span><span class="fu">is.na</span>(data8_with_crossings<span class="sc">$</span>Crossing), ]</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(crossing_points8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>AIS Mandarine Global Transition</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile sur 7 jours</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>sma_7 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data9<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">7</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer la moyenne mobile 30 jours</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>sma_30 <span class="ot">&lt;-</span> <span class="fu">SMA</span>(data9<span class="sc">$</span>Close, <span class="at">n =</span> <span class="dv">30</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Identifier les croisements entre les moyennes mobiles</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(sma_7 <span class="sc">&gt;</span> sma_30, <span class="st">"Au-dessus"</span>, <span class="st">"En dessous"</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>crossings <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, crossings[<span class="sc">-</span><span class="fu">length</span>(crossings)])  <span class="co"># décaler le vecteur d'une période</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer un data frame avec les données et les croisements</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>data9_with_crossings <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Date =</span> <span class="fu">index</span>(data9),</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Close =</span> data9<span class="sc">$</span>Close,</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_7 =</span> sma_7,</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">SMA_30 =</span> sma_30,</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Crossing =</span> crossings)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les observations avec des croisements</span></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>crossing_points9 <span class="ot">&lt;-</span> data9_with_crossings[<span class="sc">!</span><span class="fu">is.na</span>(data9_with_crossings<span class="sc">$</span>Crossing), ]</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(crossing_points9)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="conclusion-1" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-1">Conclusion</h4>
<p>“Comme en septembre, notre projection s’inscrit dans un contexte géopolitique très incertain, du fait notamment de la guerre en Ukraine et des tensions entre les États-Unis et la Chine, mais aussi à présent de la situation au Proche-Orient. Une aggravation de ces différentes tensions pourrait avoir des conséquences sur les prix du pétrole et du gaz, le commerce mondial et le niveau d’incertitude. Cela représente un aléa à la hausse sur l’inflation et à la baisse sur la croissance du PIB.</p>
<p>Plus spécifique à la France, il existe toujours un aléa à la hausse sur la consommation, dans le cas où le taux d’épargne reviendrait plus rapidement vers son niveau pré-Covid. En ce qui concerne l’inflation, il est possible que les négociations commerciales aient des effets plus importants à la baisse sur les prix de l’alimentation. De façon plus générale, il est également possible que la baisse des prix de l’énergie et les effets de la politique monétaire entraînent une décélération plus rapide des prix à la consommation dans leur ensemble.</p>
<p>L’évolution de l’investissement des entreprises est également sujette à des aléas. D’abord, les entreprises feront face à une charge d’intérêt en hausse à mesure qu’elles renouvelleront leurs emprunts à des taux plus élevés que par le passé. Cette charge financière accrue pourrait peser sur leurs embauches et leurs dépenses d’investissement. À l’inverse, la résilience de l’investissement, qui a souvent surpris par le passé, pourrait se poursuivre dans les trimestres à venir, en lien avec les besoins d’investissement dans la transition numérique et écologique.”</p>
<p>D’après la publication du 19/12/23 du site la Banque de France, <strong>Projections macroéconomiques – Décembre 2023</strong>, section “Par rapport à notre projection centrale, les aléas apparaissent dans l’ensemble légèrement négatifs sur l’activité et équilibrés sur l’inflation”. https://www.banque-france.fr/fr/publications-et-statistiques/publications/projections-macroeconomiques-decembre-2023</p>
</section>
</section>
<section id="représentez-les-boites-à-moustaches-associées-à-la-distribution-de-chaque-fonds.-commentez." class="level3">
<h3 class="anchored" data-anchor-id="représentez-les-boites-à-moustaches-associées-à-la-distribution-de-chaque-fonds.-commentez.">4. Représentez les boites à moustaches associées à la distribution de chaque fonds. Commentez.</h3>
<p>Les statistiques fournies par les boîtes à moustaches pour chaque fonds permettent d’avoir un aperçu de la distribution des prix de clôture tout au long de l’année 2023.</p>
<p><strong>Amundi CPR Climate Action I</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot pour data1</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(data1<span class="sc">$</span>Close,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Prix des titres Amundi CPR Climate Action I"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Amundi CPR Climate Action I"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Prix de clôture"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les statistiques des boîtes à moustaches</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>stats_data1 <span class="ot">&lt;-</span> <span class="fu">boxplot.stats</span>(data1<span class="sc">$</span>Close)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>stats_data1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$stats
[1] 1254.45 1303.62 1333.43 1356.61 1418.11

$n
[1] 233

$conf
[1] 1327.945 1338.915

$out
numeric(0)</code></pre>
</div>
</div>
<p>Les prix de clôture semblent être répartis sur une plage relativement étroite, avec une médiane à environ 1303.62. Cela suggère une certaine stabilité dans les prix tout au long de l’année, bien que la dispersion des données soit perceptible.</p>
<p><strong>MainFirst Global Equities X</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$stats
[1] 119.500 126.995 130.995 135.580 143.120

$n
[1] 236

$conf
[1] 130.112 131.878

$out
numeric(0)</code></pre>
</div>
</div>
<p>La médiane des prix est d’environ 126.995, avec une plage assez large allant de 119.500 à 143.120. Cela indique une plus grande variabilité dans les prix par rapport au fonds précédent.</p>
<p><strong>The Andersons : (ANDE)</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$stats
[1] 33.47 40.78 46.36 50.89 58.57

$n
[1] 250

$conf
[1] 45.34973 47.37027

$out
numeric(0)</code></pre>
</div>
</div>
<p>Avec une médiane à environ 40.78, les prix de clôture pour ce fonds sont significativement plus bas que les deux précédents. La plage de variation est également plus large, ce qui suggère une plus grande volatilité dans les prix.</p>
<p><strong>Carmignac Emergents</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$stats
[1] 141.24 147.94 150.90 153.61 160.71

$n
[1] 249

$conf
[1] 150.3323 151.4677

$out
numeric(0)</code></pre>
</div>
</div>
<p>Ce fonds affiche une médiane à environ 147.94, avec une plage de variation plus étroite par rapport à certains autres fonds. Cela peut indiquer une certaine stabilité relative dans les prix de clôture.</p>
<p><strong>Pluvalca Sustainable Opportunities</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$stats
[1] 115.75 131.53 139.29 142.78 151.71

$n
[1] 249

$conf
[1] 138.1635 140.4164

$out
numeric(0)</code></pre>
</div>
</div>
<p>Les prix de clôture pour ce fonds ont une médiane à environ 131.53, avec une plage de variation similaire à celle de Carmignac Emergents. Cependant, la médiane est plus élevée, suggérant des prix plus élevés en moyenne.</p>
<p><strong>Fidelity Sustainable Water &amp; Waste R Acc</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$stats
[1]  92.900  96.605  98.120  99.960 104.800

$n
[1] 251

$conf
[1] 97.78541 98.45459

$out
 [1]  91.56  90.25  90.45  91.19  90.08  90.85  90.78  90.96  91.53 105.10
[11] 105.10 105.20</code></pre>
</div>
</div>
<p>La médiane des prix est d’environ 96.605, avec une plage de variation plus large allant de 90.08 à 105.20. Cela indique une certaine volatilité dans les prix de clôture pour ce fonds.</p>
<p><strong>Epsens EdR Tricolore Rendement</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$stats
[1] 14.448 15.373 15.751 15.990 16.373

$n
[1] 249

$conf
[1] 15.68922 15.81278

$out
[1] 14.438 14.420</code></pre>
</div>
</div>
<p>Ce fonds présente une médiane à environ 15.373, avec une plage de variation relativement étroite. Les prix de clôture sont nettement plus bas que ceux des autres fonds, ce qui peut refléter une catégorie d’actifs différente ou une performance différente.</p>
<p><strong>Thematics Water R/A USD</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$stats
[1] 22.90639 24.37694 24.83153 25.36184 26.68461

$n
[1] 249

$conf
[1] 24.73291 24.93015

$out
numeric(0)</code></pre>
</div>
</div>
<p>Avec une médiane à environ 24.37694, ce fonds affiche une plage de variation relativement étroite par rapport à certains autres fonds. Cependant, la médiane est plus élevée, suggérant des prix plus élevés en moyenne.</p>
<p><strong>AIS Mandarine Global Transition</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$stats
[1] 75.180 79.595 81.180 82.720 85.030

$n
[1] 247

$conf
[1] 80.86583 81.49417

$out
[1] 74.10 73.75 74.05 74.33 74.39 74.14 74.35</code></pre>
</div>
</div>
<p>Ce fonds présente une médiane à environ 79.595, avec une plage de variation relativement étroite. Les prix de clôture sont significativement plus élevés que ceux d’autres fonds, indiquant une catégorie d’actifs ou une performance différente.</p>
<section id="conclusion-2" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-2">Conclusion</h4>
<p>En résumé, l’analyse des statistiques des boîtes à moustaches pour chaque fonds permet de mieux comprendre la distribution des prix de clôture et la volatilité associée à chaque fonds tout au long de l’année 2023.</p>
</section>
</section>
<section id="calculer-les-statistiques-descriptives-univariées-moyenne-variance-écart-type-asymétrie-kurtosis-pour-chaque-fonds-et-commenter-les-résultats.-quels-fonds-ont-le-rendement-moyen-le-plus-élevé-et-le-plus-faible-quels-fonds-ont-lécart-type-le-plus-élevé-et-le-plus-faible-quelles-séries-semblent-les-plus-et-les-moins-distribués-normalement" class="level3">
<h3 class="anchored" data-anchor-id="calculer-les-statistiques-descriptives-univariées-moyenne-variance-écart-type-asymétrie-kurtosis-pour-chaque-fonds-et-commenter-les-résultats.-quels-fonds-ont-le-rendement-moyen-le-plus-élevé-et-le-plus-faible-quels-fonds-ont-lécart-type-le-plus-élevé-et-le-plus-faible-quelles-séries-semblent-les-plus-et-les-moins-distribués-normalement">5. Calculer les statistiques descriptives univariées (moyenne, variance, écart-type, asymétrie, kurtosis) pour chaque fonds et commenter les résultats. Quels fonds ont le rendement moyen le plus élevé et le plus faible ? Quels fonds ont l’écart type le plus élevé et le plus faible ? Quelles séries semblent les plus et les moins distribués normalement ?</h3>
<p>Les résultats des statistiques descriptives univariées fournissent des informations précieuses sur la distribution des rendements pour chaque fonds.</p>
<p><strong>Amundi CPR Climate Action I</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Supprimer les lignes contenant des valeurs manquantes</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>data1_clean <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(data1)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir les colonnes autres que la colonne Date en type numérique</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>data1_clean[, <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">sapply</span>(data1_clean[, <span class="sc">-</span><span class="dv">1</span>], as.numeric)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les statistiques descriptives pour chaque fonds</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>stats_data1 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Mean =</span> <span class="fu">colMeans</span>(data1_clean[, <span class="sc">-</span><span class="dv">1</span>]),  <span class="co"># Exclure la colonne Date</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variance =</span> <span class="fu">sapply</span>(data1_clean[, <span class="sc">-</span><span class="dv">1</span>], var),</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Std_Deviation =</span> <span class="fu">sapply</span>(data1_clean[, <span class="sc">-</span><span class="dv">1</span>], sd),</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">Skewness =</span> <span class="fu">sapply</span>(data1_clean[, <span class="sc">-</span><span class="dv">1</span>], skewness),</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">Kurtosis =</span> <span class="fu">sapply</span>(data1_clean[, <span class="sc">-</span><span class="dv">1</span>], kurtosis)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les statistiques descriptives</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>stats_data1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Mean     Variance Std_Deviation    Skewness Kurtosis
Open      1.331683e+03 1.281334e+03  35.795719314  0.05039511 2.551901
High      1.331683e+03 1.281334e+03  35.795719314  0.05039511 2.551901
Low       1.331683e+03 1.281334e+03  35.795719314  0.05039511 2.551901
Close     1.331683e+03 1.281334e+03  35.795719314  0.05039511 2.551901
Adj Close 1.331208e+03 1.319515e+03  36.325134040  0.02745093 2.530950
Volume    0.000000e+00 0.000000e+00   0.000000000         NaN      NaN
Rendement 5.278844e-04 4.973462e-05   0.007052277 -0.63859837 6.596489</code></pre>
</div>
</div>
<p><strong>MainFirst Global Equities X</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                  Mean     Variance Std_Deviation    Skewness Kurtosis
Open      1.312328e+02 2.809959e+01   5.300904938  0.06965733 2.032378
High      1.312328e+02 2.809959e+01   5.300904938  0.06965733 2.032378
Low       1.312328e+02 2.809959e+01   5.300904938  0.06965733 2.032378
Close     1.312328e+02 2.809959e+01   5.300904938  0.06965733 2.032378
Adj Close 1.310148e+02 2.967529e+01   5.447502922  0.07433636 2.017350
Volume    0.000000e+00 0.000000e+00   0.000000000         NaN      NaN
Rendement 6.633825e-04 9.531755e-05   0.009763071 -0.09038927 3.084972</code></pre>
</div>
</div>
<p>Le fonds MainFirst Global Equities X a l’écart-type le plus faible parmi les fonds, ce qui indique une dispersion moindre des rendements autour de la moyenne.</p>
<p><strong>The Andersons : (ANDE)</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                  Mean     Variance Std_Deviation   Skewness  Kurtosis
Open      4.579216e+01 3.583963e+01  5.986621e+00 -0.2415392  1.941619
High      4.642004e+01 3.600115e+01  6.000096e+00 -0.2547723  1.985360
Low       4.514712e+01 3.542087e+01  5.951544e+00 -0.2138271  1.932470
Close     4.587036e+01 3.584069e+01  5.986710e+00 -0.2445914  1.998865
Adj Close 4.548380e+01 3.729465e+01  6.106935e+00 -0.2287445  1.973429
Volume    2.217300e+05 2.335597e+10  1.528266e+05  5.8009077 54.208958
Rendement 2.358979e-03 4.998785e-04  2.235796e-02  0.1063399 13.606239</code></pre>
</div>
</div>
<p><strong>Carmignac Emergents</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                  Mean     Variance Std_Deviation   Skewness Kurtosis
Open      1.507192e+02 1.569517e+01   3.961712684 -0.1249409 2.456043
High      1.507192e+02 1.569517e+01   3.961712684 -0.1249409 2.456043
Low       1.507192e+02 1.569517e+01   3.961712684 -0.1249409 2.456043
Close     1.507192e+02 1.569517e+01   3.961712684 -0.1249409 2.456043
Adj Close 1.500969e+02 1.548821e+01   3.935506955 -0.3099695 2.322901
Volume    0.000000e+00 0.000000e+00   0.000000000        NaN      NaN
Rendement 3.645943e-04 8.582018e-05   0.009263918  0.2726240 3.045324</code></pre>
</div>
</div>
<p>Le fonds Carmignac Emergents semble avoir le rendement moyen le plus élevé parmi les fonds analysés, avec une moyenne de 0.000365, suivi par AIS Mandarine Global Transition avec une moyenne de 0.000235.</p>
<p><strong>Pluvalca Sustainable Opportunities</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                   Mean     Variance Std_Deviation   Skewness Kurtosis
Open       1.375247e+02 7.581495e+01   8.707178155 -0.5575162 2.695239
High       1.375247e+02 7.581495e+01   8.707178155 -0.5575162 2.695239
Low        1.375247e+02 7.581495e+01   8.707178155 -0.5575162 2.695239
Close      1.375247e+02 7.581495e+01   8.707178155 -0.5575162 2.695239
Adj Close  1.375247e+02 7.581495e+01   8.707178155 -0.5575162 2.695239
Volume     0.000000e+00 0.000000e+00   0.000000000        NaN      NaN
Rendement -6.023230e-05 9.494650e-05   0.009744049 -0.1594337 4.312768</code></pre>
</div>
</div>
<p>Le fonds Pluvalca Sustainable Opportunities présente l’écart-type le plus élevé parmi les fonds, ce qui suggère une plus grande variabilité dans ses rendements.</p>
<p><strong>Fidelity Sustainable Water &amp; Waste R Acc</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                  Mean     Variance Std_Deviation   Skewness Kurtosis
Open      98.190756944 7.999469e+00   2.828333276 -0.2191285 3.504728
High      98.190756944 7.999469e+00   2.828333276 -0.2191285 3.504728
Low       98.190756944 7.999469e+00   2.828333276 -0.2191285 3.504728
Close     98.190756944 7.999469e+00   2.828333276 -0.2191285 3.504728
Adj Close 98.178885657 7.993617e+00   2.827298561 -0.2194294 3.505485
Volume     0.000000000 0.000000e+00   0.000000000        NaN      NaN
Rendement  0.000473013 6.787794e-05   0.008238807  0.2229338 3.602530</code></pre>
</div>
</div>
<p>Le fonds Fidelity Sustainable Water &amp; Waste R Acc affiche le rendement moyen le plus faible parmi les fonds analysés, avec une moyenne de 0.000473.</p>
<p><strong>Epsens EdR Tricolore Rendement</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                  Mean     Variance Std_Deviation   Skewness Kurtosis
Open      1.565449e+01 0.1958295500   0.442526327 -0.8094600 3.048294
High      1.565449e+01 0.1958295500   0.442526327 -0.8094600 3.048294
Low       1.565449e+01 0.1958295500   0.442526327 -0.8094600 3.048294
Close     1.565449e+01 0.1958295500   0.442526327 -0.8094600 3.048294
Adj Close 1.565449e+01 0.1958295500   0.442526327 -0.8094600 3.048294
Volume    0.000000e+00 0.0000000000   0.000000000        NaN      NaN
Rendement 5.103783e-04 0.0000774436   0.008800204 -0.4965516 4.601074</code></pre>
</div>
</div>
<p><strong>Thematics Water R/A USD</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                  Mean     Variance Std_Deviation    Skewness Kurtosis
Open      2.485502e+01 5.263139e-01   0.725474916  0.11246124 3.378091
High      2.485502e+01 5.263139e-01   0.725474916  0.11246124 3.378091
Low       2.485502e+01 5.263139e-01   0.725474916  0.11246124 3.378091
Close     2.485502e+01 5.263139e-01   0.725474916  0.11246124 3.378091
Adj Close 2.485502e+01 5.263139e-01   0.725474916  0.11246124 3.378091
Volume    0.000000e+00 0.000000e+00   0.000000000         NaN      NaN
Rendement 5.239156e-04 6.230871e-05   0.007893587 -0.01193903 3.658727</code></pre>
</div>
</div>
<p><strong>AIS Mandarine Global Transition</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                  Mean     Variance Std_Deviation   Skewness Kurtosis
Open      8.090332e+01 5.603185e+00   2.367104839 -0.8253939 3.390643
High      8.090332e+01 5.603185e+00   2.367104839 -0.8253939 3.390643
Low       8.090332e+01 5.603185e+00   2.367104839 -0.8253939 3.390643
Close     8.090332e+01 5.603185e+00   2.367104839 -0.8253939 3.390643
Adj Close 8.090332e+01 5.603185e+00   2.367104839 -0.8253939 3.390643
Volume    0.000000e+00 0.000000e+00   0.000000000        NaN      NaN
Rendement 2.350869e-04 5.052724e-05   0.007108251 -0.1879644 3.501860</code></pre>
</div>
</div>
<section id="conclusion-3" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-3">Conclusion</h4>
<p>La plupart des fonds semblent avoir une légère asymétrie vers la gauche (skewness négatif), indiquant une légère queue plus longue du côté gauche de la distribution des rendements.</p>
<p>Les valeurs de kurtosis pour la plupart des fonds dépassent 3, ce qui suggère une distribution des rendements plus leptokurtique (plus de poids sur les queues) par rapport à une distribution normale. Les fonds Pluvalca Sustainable Opportunities et The Andersons semblent être les moins distribués normalement en raison de leurs valeurs de skewness et de kurtosis élevées.</p>
<p>Les fonds MainFirst Global Equities X et Thematics Water R/A USD semblent être les plus distribués normalement parmi ceux analysés, avec des valeurs de skewness et de kurtosis plus proches de zéro. En résumé, ces statistiques permettent de comparer la distribution des rendements entre les différents fonds, mettant en évidence leurs caractéristiques distinctives en termes de rendement moyen, volatilité et forme de distribution.</p>
</section>
</section>
<section id="en-utilisant-un-taux-mensuel-sans-risque-égal-à-05-par-mois-ce-qui-correspond-à-un-taux-annuel-composé-en-continu-de-62-calculer-le-ratio-de-sharpe-pour-chaque-actif.-commenter." class="level3">
<h3 class="anchored" data-anchor-id="en-utilisant-un-taux-mensuel-sans-risque-égal-à-05-par-mois-ce-qui-correspond-à-un-taux-annuel-composé-en-continu-de-62-calculer-le-ratio-de-sharpe-pour-chaque-actif.-commenter.">6. En utilisant un taux mensuel sans risque égal à 0,5% par mois (ce qui correspond à un taux annuel composé en continu de 6,2%), calculer le ratio de Sharpe pour chaque actif. Commenter.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Taux mensuel sans risque</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>risk_free_rate <span class="ot">&lt;-</span> <span class="fl">0.005</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul du ratio de Sharpe pour chaque actif</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>sharpe_ratios <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">mean</span>(data1_clean<span class="sc">$</span>Rendement) <span class="sc">-</span> risk_free_rate) <span class="sc">/</span> <span class="fu">sd</span>(data1_clean<span class="sc">$</span>Rendement),</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">mean</span>(data2_clean<span class="sc">$</span>Rendement) <span class="sc">-</span> risk_free_rate) <span class="sc">/</span> <span class="fu">sd</span>(data2_clean<span class="sc">$</span>Rendement),</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">mean</span>(data3_clean<span class="sc">$</span>Rendement) <span class="sc">-</span> risk_free_rate) <span class="sc">/</span> <span class="fu">sd</span>(data3_clean<span class="sc">$</span>Rendement),</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">mean</span>(data4_clean<span class="sc">$</span>Rendement) <span class="sc">-</span> risk_free_rate) <span class="sc">/</span> <span class="fu">sd</span>(data4_clean<span class="sc">$</span>Rendement),</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">mean</span>(data5_clean<span class="sc">$</span>Rendement) <span class="sc">-</span> risk_free_rate) <span class="sc">/</span> <span class="fu">sd</span>(data5_clean<span class="sc">$</span>Rendement),</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">mean</span>(data6_clean<span class="sc">$</span>Rendement) <span class="sc">-</span> risk_free_rate) <span class="sc">/</span> <span class="fu">sd</span>(data6_clean<span class="sc">$</span>Rendement),</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">mean</span>(data7_clean<span class="sc">$</span>Rendement) <span class="sc">-</span> risk_free_rate) <span class="sc">/</span> <span class="fu">sd</span>(data7_clean<span class="sc">$</span>Rendement),</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">mean</span>(data8_clean<span class="sc">$</span>Rendement) <span class="sc">-</span> risk_free_rate) <span class="sc">/</span> <span class="fu">sd</span>(data8_clean<span class="sc">$</span>Rendement),</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">mean</span>(data9_clean<span class="sc">$</span>Rendement) <span class="sc">-</span> risk_free_rate) <span class="sc">/</span> <span class="fu">sd</span>(data9_clean<span class="sc">$</span>Rendement)</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Les ratios de Sharpes sont présentés dans le même ordre depuis le début de l’exercice et le seront également pour les questions suivantes. Voici l’ordre en question : 1. Amundi CPR Climate Action I 2. MainFirst Global Equities X 3. The Andersons : (ANDE) 4. Carmignac Emergents 5. Pluvalca Sustainable Opportunities 6. Fidelity Sustainable Water &amp; Waste R Acc 7. Epsens EdR Tricolore Rendement 8. Thematics Water R/A USD 9. AIS Mandarine Global Transition</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.6341378 -0.4441858 -0.1181244 -0.5003720 -0.5193151 -0.5494712 -0.5101724
[8] -0.5670533 -0.6703355</code></pre>
</div>
</div>
<section id="conclusion-4" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-4">Conclusion</h4>
<p>Ces valeurs négatives indiquent que le rendement excédentaire par rapport au taux sans risque n’est pas suffisant pour compenser le risque pris par rapport à la volatilité de chaque actif. Un ratio de Sharpe positif est généralement préférable, ce qui indiquerait un rendement excédentaire adéquat par rapport au risque.</p>
<p>Les ratios de Sharpe calculés pour chaque actif sont tous négatifs, ce qui signifie que le rendement excédentaire par rapport au taux sans risque n’est pas suffisant pour compenser le risque pris par rapport à la volatilité de chaque actif. Un ratio de Sharpe positif est généralement préférable, car il indique un rendement excédentaire adéquat par rapport au risque.</p>
<p>Parmi les actifs analysés, aucun ne semble offrir un rendement ajusté au risque satisfaisant, ce qui peut être un indicateur de sous-performance par rapport à un investissement sans risque, du moins sur la période considérée. Cela pourrait inciter les investisseurs à revoir leur allocation d’actifs ou leur stratégie d’investissement, en cherchant peut-être des opportunités offrant un meilleur rapport risque-rendement.</p>
</section>
</section>
<section id="déterminez-la-matrice-de-variances-covariances-des-rendements-de-vos-neuf-actifs-et-commenter" class="level3">
<h3 class="anchored" data-anchor-id="déterminez-la-matrice-de-variances-covariances-des-rendements-de-vos-neuf-actifs-et-commenter">7. Déterminez la matrice de variances-covariances des rendements de vos neuf actifs et commenter</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de la matrice de variances-covariances des rendements des neuf actifs</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>cov_matrix <span class="ot">&lt;-</span> <span class="fu">cov</span>(<span class="fu">cbind</span>(data1_clean<span class="sc">$</span>Rendement, data2_clean<span class="sc">$</span>Rendement, data3_clean<span class="sc">$</span>Rendement, </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                        data4_clean<span class="sc">$</span>Rendement, data5_clean<span class="sc">$</span>Rendement, data6_clean<span class="sc">$</span>Rendement, </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>                        data7_clean<span class="sc">$</span>Rendement, data8_clean<span class="sc">$</span>Rendement, data9_clean<span class="sc">$</span>Rendement))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>               [,1]          [,2]         [,3]          [,4]          [,5]
 [1,]  4.881402e-05  1.988060e-05 6.636493e-06  8.443968e-07 -4.512467e-06
 [2,]  1.988060e-05  9.249051e-05 6.792256e-06 -1.507628e-06 -1.233212e-06
 [3,]  6.636493e-06  6.792256e-06 4.979012e-04  2.581870e-05  1.527750e-05
 [4,]  8.443968e-07 -1.507628e-06 2.581870e-05  8.611262e-05  2.649835e-05
 [5,] -4.512467e-06 -1.233212e-06 1.527750e-05  2.649835e-05  9.428806e-05
 [6,]  6.184643e-06  9.321864e-06 1.760002e-05  1.670788e-05  1.082296e-05
 [7,] -3.244077e-06  1.957923e-06 2.544074e-06  1.837640e-05  7.030567e-05
 [8,]  1.514154e-06  5.274762e-06 1.288287e-05  2.572957e-05  4.281635e-05
 [9,] -5.218657e-06  1.008173e-06 3.791192e-06  1.098916e-05  1.968526e-05
              [,6]          [,7]         [,8]          [,9]
 [1,] 6.184643e-06 -3.244077e-06 1.514154e-06 -5.218657e-06
 [2,] 9.321864e-06  1.957923e-06 5.274762e-06  1.008173e-06
 [3,] 1.760002e-05  2.544074e-06 1.288287e-05  3.791192e-06
 [4,] 1.670788e-05  1.837640e-05 2.572957e-05  1.098916e-05
 [5,] 1.082296e-05  7.030567e-05 4.281635e-05  1.968526e-05
 [6,] 6.787794e-05  1.309900e-05 2.146665e-05  1.864513e-05
 [7,] 1.309900e-05  7.688219e-05 3.780027e-05  2.017466e-05
 [8,] 2.146665e-05  3.780027e-05 6.254721e-05  2.491438e-05
 [9,] 1.864513e-05  2.017466e-05 2.491438e-05  5.027083e-05</code></pre>
</div>
</div>
<section id="conclusion-5" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-5">Conclusion</h4>
<p>La matrice de variances-covariances des rendements des neuf actifs est symétrique, ce qui est conforme aux propriétés des matrices de covariances. Les valeurs sur la diagonale représentent les variances des rendements de chaque actif, tandis que les valeurs hors diagonale représentent les covariances entre les rendements des différents actifs.</p>
<p>Une covariance positive entre les rendements de deux actifs indique une relation linéaire positive, ce qui signifie que les rendements de ces actifs ont tendance à évoluer dans le même sens. À l’inverse, une covariance négative indique une relation linéaire négative, ce qui signifie que les rendements des actifs ont tendance à évoluer dans des directions opposées.</p>
<p>En regardant la matrice, on peut observer que les variances des rendements des actifs se situent sur la diagonale principale, tandis que les covariances entre les rendements des différents actifs sont situées en dehors de la diagonale. Les valeurs de covariances indiquent à quel point les rendements des actifs sont corrélés les uns par rapport aux autres.</p>
</section>
</section>
<section id="calculer-la-matrice-de-corrélation-des-rendements-de-vos-neuf-actifs-et-tracer-cette-matrice-de-corrélation-à-laide-de-la-fonction-corrplot-du-package-corrplot." class="level3">
<h3 class="anchored" data-anchor-id="calculer-la-matrice-de-corrélation-des-rendements-de-vos-neuf-actifs-et-tracer-cette-matrice-de-corrélation-à-laide-de-la-fonction-corrplot-du-package-corrplot.">8. Calculer la matrice de corrélation des rendements de vos neuf actifs et tracer cette matrice de corrélation à l’aide de la fonction corrplot du package corrplot.</h3>
</section>
<section id="quels-actifs-sont-les-plus-fortement-corrélés-quels-sont-les-moins-corrélés-daprès-les-valeurs-de-corrélations-estimées-pensez-vous-que-la-diversification-réduira-le-risque-avec-ces-actifs" class="level3">
<h3 class="anchored" data-anchor-id="quels-actifs-sont-les-plus-fortement-corrélés-quels-sont-les-moins-corrélés-daprès-les-valeurs-de-corrélations-estimées-pensez-vous-que-la-diversification-réduira-le-risque-avec-ces-actifs">9. Quels actifs sont les plus fortement corrélés ? Quels sont les moins corrélés ? D’après les valeurs de corrélations estimées, pensez-vous que la diversification réduira le risque avec ces actifs ?</h3>
<p>Pour identifier les actifs les plus fortement corrélés, nous pouvons examiner les valeurs les plus proches de 1 dans la matrice de corrélation. De même, les actifs les moins corrélés auront des valeurs proches de 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de la matrice de corrélation des rendements des neuf actifs</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(<span class="fu">cbind</span>(data1_clean<span class="sc">$</span>Rendement, data2_clean<span class="sc">$</span>Rendement, data3_clean<span class="sc">$</span>Rendement,data4_clean<span class="sc">$</span>Rendement, data5_clean<span class="sc">$</span>Rendement, data6_clean<span class="sc">$</span>Rendement, data7_clean<span class="sc">$</span>Rendement, data8_clean<span class="sc">$</span>Rendement, data9_clean<span class="sc">$</span>Rendement))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             [,1]        [,2]       [,3]        [,4]        [,5]       [,6]
 [1,]  1.00000000  0.29587524 0.04256913  0.01302390 -0.06651405 0.10744297
 [2,]  0.29587524  1.00000000 0.03165147 -0.01689321 -0.01320568 0.11764943
 [3,]  0.04256913  0.03165147 1.00000000  0.12468936  0.07051026 0.09573643
 [4,]  0.01302390 -0.01689321 0.12468936  1.00000000  0.29407429 0.21853635
 [5,] -0.06651405 -0.01320568 0.07051026  0.29407429  1.00000000 0.13528618
 [6,]  0.10744297  0.11764943 0.09573643  0.21853635  0.13528618 1.00000000
 [7,] -0.05295488  0.02321849 0.01300305  0.22584688  0.82575100 0.18132634
 [8,]  0.02740272  0.06935062 0.07300239  0.35058653  0.55754159 0.32945494
 [9,] -0.10534851  0.01478524 0.02396327  0.16702179  0.28592678 0.31918547
             [,7]       [,8]        [,9]
 [1,] -0.05295488 0.02740272 -0.10534851
 [2,]  0.02321849 0.06935062  0.01478524
 [3,]  0.01300305 0.07300239  0.02396327
 [4,]  0.22584688 0.35058653  0.16702179
 [5,]  0.82575100 0.55754159  0.28592678
 [6,]  0.18132634 0.32945494  0.31918547
 [7,]  1.00000000 0.54510237  0.32451537
 [8,]  0.54510237 1.00000000  0.44431206
 [9,]  0.32451537 0.44431206  1.00000000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tracé de la matrice de corrélation à l'aide de la fonction corrplot</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, <span class="at">method =</span> <span class="st">"color"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="conclusion-6" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-6">Conclusion</h4>
<p>En examinant la matrice de corrélation, nous pouvons observer que les actifs les plus fortement corrélés sont ceux avec des valeurs proches de 1 sur la diagonale principale de la matrice. Dans ce cas, les actifs les plus corrélés sont le 5ème et le 7ème actif, avec une corrélation de 0.83.</p>
<p>Les actifs les moins corrélés sont ceux avec des valeurs proches de 0 dans la matrice. Par exemple, les actifs 1 et 9 semblent être les moins corrélés, avec une corrélation de -0.11.</p>
<p>En termes de diversification, la corrélation entre les actifs joue un rôle crucial. Une diversification efficace suppose que les actifs inclus dans un portefeuille ont des corrélations faibles ou négatives, car cela signifie qu’ils ne réagissent pas de la même manière aux mêmes conditions de marché. Cela réduit le risque global du portefeuille. Dans ce cas, puisque les actifs présentent des corrélations positives relativement élevées, la diversification seule ne réduira pas considérablement le risque, car les actifs ont tendance à se déplacer dans la même direction sous certaines conditions du marché. Cependant, une diversification peut encore offrir certains avantages, bien que plus limités, en répartissant le risque sur différents actifs.</p>
</section>
</section>
<section id="a-partir-de-7-mesures-de-performances-ajustées-au-risque-identifier-pour-chacune-delle-le-titre-le-plus-rentable." class="level3">
<h3 class="anchored" data-anchor-id="a-partir-de-7-mesures-de-performances-ajustées-au-risque-identifier-pour-chacune-delle-le-titre-le-plus-rentable.">10. A partir de 7 mesures de performances ajustées au risque, identifier pour chacune d’elle, le titre le plus rentable.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définition des valeurs de référence</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fl">1.2</span>  <span class="co"># Exemple de coefficient bêta</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>mean_market_return <span class="ot">&lt;-</span> <span class="fl">0.08</span>  <span class="co"># Exemple de rendement moyen du marché</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>mean_benchmark_return <span class="ot">&lt;-</span> <span class="fl">0.06</span>  <span class="co"># Exemple de rendement moyen de l'indice de référence</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des mesures de performance ajustées au risque pour chaque actif</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Création d'une fonction pour calculer les mesures de performance ajustées au risque</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>calculate_performance <span class="ot">&lt;-</span> <span class="cf">function</span>(returns, risk_free_rate) {</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  mean_return <span class="ot">&lt;-</span> <span class="fu">mean</span>(returns)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>  volatility <span class="ot">&lt;-</span> <span class="fu">sd</span>(returns)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>  sharpe_ratio <span class="ot">&lt;-</span> (mean_return <span class="sc">-</span> risk_free_rate) <span class="sc">/</span> volatility</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>  sortino_ratio <span class="ot">&lt;-</span> (mean_return <span class="sc">-</span> risk_free_rate) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(<span class="fu">pmin</span>(returns <span class="sc">-</span> risk_free_rate, <span class="dv">0</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">length</span>(returns))</span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  treynor_ratio <span class="ot">&lt;-</span> (mean_return <span class="sc">-</span> risk_free_rate) <span class="sc">/</span> beta</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>  jensen_alpha <span class="ot">&lt;-</span> mean_return <span class="sc">-</span> risk_free_rate <span class="sc">-</span> beta <span class="sc">*</span> (mean_market_return <span class="sc">-</span> risk_free_rate)</span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>  information_ratio <span class="ot">&lt;-</span> (mean_return <span class="sc">-</span> mean_benchmark_return) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((returns <span class="sc">-</span> mean_return)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>  omega_ratio <span class="ot">&lt;-</span> <span class="fu">mean</span>(returns) <span class="sc">/</span> (<span class="fu">sqrt</span>(<span class="fu">sum</span>(<span class="fu">pmin</span>(returns, <span class="dv">0</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">length</span>(returns)))</span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">list</span>(</span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sharpe_Ratio =</span> sharpe_ratio,</span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sortino_Ratio =</span> sortino_ratio,</span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">Treynor_Ratio =</span> treynor_ratio,</span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">Jensen_Alpha =</span> jensen_alpha,</span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">Information_Ratio =</span> information_ratio,</span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">Omega_Ratio =</span> omega_ratio</span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-30"><a href="#cb42-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Définition du taux sans risque</span></span>
<span id="cb42-31"><a href="#cb42-31" aria-hidden="true" tabindex="-1"></a>risk_free_rate <span class="ot">&lt;-</span> <span class="fl">0.005</span></span>
<span id="cb42-32"><a href="#cb42-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-33"><a href="#cb42-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des mesures de performance ajustées au risque pour chaque actif</span></span>
<span id="cb42-34"><a href="#cb42-34" aria-hidden="true" tabindex="-1"></a>performance_data <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb42-35"><a href="#cb42-35" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>) {</span>
<span id="cb42-36"><a href="#cb42-36" aria-hidden="true" tabindex="-1"></a>  returns <span class="ot">&lt;-</span> <span class="fu">get</span>(<span class="fu">paste0</span>(<span class="st">"data"</span>, i, <span class="st">"_clean"</span>))<span class="sc">$</span>Rendement</span>
<span id="cb42-37"><a href="#cb42-37" aria-hidden="true" tabindex="-1"></a>  performance_data[[<span class="fu">paste0</span>(<span class="st">"data"</span>, i)]] <span class="ot">&lt;-</span> <span class="fu">calculate_performance</span>(returns, risk_free_rate)</span>
<span id="cb42-38"><a href="#cb42-38" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb42-39"><a href="#cb42-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-40"><a href="#cb42-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Identifier le titre le plus rentable pour chaque mesure de performance</span></span>
<span id="cb42-41"><a href="#cb42-41" aria-hidden="true" tabindex="-1"></a>best_performers <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb42-42"><a href="#cb42-42" aria-hidden="true" tabindex="-1"></a>metrics <span class="ot">&lt;-</span> <span class="fu">names</span>(performance_data[[<span class="dv">1</span>]])  <span class="co"># Obtenez les noms des mesures de performance</span></span>
<span id="cb42-43"><a href="#cb42-43" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (metric <span class="cf">in</span> metrics) {</span>
<span id="cb42-44"><a href="#cb42-44" aria-hidden="true" tabindex="-1"></a>  best_performer <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">which.max</span>(<span class="fu">sapply</span>(performance_data, <span class="cf">function</span>(x) x[[metric]])))</span>
<span id="cb42-45"><a href="#cb42-45" aria-hidden="true" tabindex="-1"></a>  best_performers[[metric]] <span class="ot">&lt;-</span> best_performer</span>
<span id="cb42-46"><a href="#cb42-46" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb42-47"><a href="#cb42-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-48"><a href="#cb42-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Afficher les titres les plus rentables pour chaque mesure de performance</span></span>
<span id="cb42-49"><a href="#cb42-49" aria-hidden="true" tabindex="-1"></a>best_performers</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Sharpe_Ratio
[1] "data3"

$Sortino_Ratio
[1] "data3"

$Treynor_Ratio
[1] "data3"

$Jensen_Alpha
[1] "data3"

$Information_Ratio
[1] "data3"

$Omega_Ratio
[1] "data3"</code></pre>
</div>
</div>
<section id="conclusion-7" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-7">Conclusion</h4>
<p>Sur la base des mesures de performance ajustées au risque calculées, le titre The Andersons : (ANDE) est identifié comme le titre le plus rentable pour toutes les mesures de performance, y compris le ratio de Sharpe, le ratio de Sortino, le ratio de Treynor, l’alpha de Jensen, le ratio d’information et le ratio d’Oméga. Cela suggère que, selon ces mesures, le titre 3 présente la meilleure performance ajustée au risque parmi les neuf actifs étudiés.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="exercice-2-théorie-moderne-de-portefeuille" class="level2">
<h2 class="anchored" data-anchor-id="exercice-2-théorie-moderne-de-portefeuille">Exercice 2 : théorie moderne de portefeuille</h2>
<section id="utilisez-les-9-actifs-précédents." class="level3">
<h3 class="anchored" data-anchor-id="utilisez-les-9-actifs-précédents.">1. Utilisez les 9 actifs précédents.</h3>
<section id="a.-calculez-le-rendement-du-portefeuille-équipondéré-composé-des-9-fonds-puis-en-déduire-son-écart-type" class="level4">
<h4 class="anchored" data-anchor-id="a.-calculez-le-rendement-du-portefeuille-équipondéré-composé-des-9-fonds-puis-en-déduire-son-écart-type">a. Calculez le rendement du portefeuille équipondéré composé des 9 fonds, puis en déduire son écart type</h4>
</section>
<section id="b.-quelles-sont-les-propriétés-financières-de-cette-série-de-rendement-obtenue" class="level4">
<h4 class="anchored" data-anchor-id="b.-quelles-sont-les-propriétés-financières-de-cette-série-de-rendement-obtenue">b. Quelles sont les propriétés financières de cette série de rendement obtenue ?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sélectionner les rendements de chaque fonds</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>returns <span class="ot">&lt;-</span> <span class="fu">cbind</span>(data1_clean<span class="sc">$</span>Rendement, data2_clean<span class="sc">$</span>Rendement, data3_clean<span class="sc">$</span>Rendement,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                 data4_clean<span class="sc">$</span>Rendement, data5_clean<span class="sc">$</span>Rendement, data6_clean<span class="sc">$</span>Rendement,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>                 data7_clean<span class="sc">$</span>Rendement, data8_clean<span class="sc">$</span>Rendement, data9_clean<span class="sc">$</span>Rendement)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les rendements du portefeuille équipondéré</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>portfolio_returns <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(returns)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer l'écart-type du portefeuille</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>portfolio_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(portfolio_returns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Rendement du portefeuille équipondéré: 0.0006853927214627"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Écart-type du portefeuille équipondéré: 0.00506315070202448"</code></pre>
</div>
</div>
<p>La série de rendements obtenue pour le portefeuille équipondéré possède plusieurs propriétés financières importantes.</p>
<p>Le rendement moyen du portefeuille équipondéré est d’environ 0.0006854. Cela indique le rendement moyen que l’investisseur peut attendre sur son investissement sur une période donnée.</p>
<p>L’écart-type du portefeuille équipondéré est d’environ 0.005063. C’est une mesure de la dispersion des rendements autour de la moyenne. Plus l’écart-type est élevé, plus les rendements sont volatils et risqués.</p>
<p>L’écart-type est également une mesure du risque du portefeuille. Un écart-type plus élevé indique un niveau de risque plus élevé, car cela signifie que les rendements sont plus volatils et moins prévisibles.</p>
<p>Le rendement moyen et l’écart-type peuvent être utilisés pour calculer des mesures de performance ajustées au risque telles que le ratio de Sharpe, le ratio de Treynor, etc. Ces mesures aident à évaluer la performance du portefeuille par rapport à son niveau de risque.</p>
<p>En combinant plusieurs actifs dans un portefeuille équipondéré, on bénéficie de la diversification, ce qui peut réduire le risque global du portefeuille. Cependant, la réduction du risque dépend de la corrélation entre les rendements des actifs individuels. Si les actifs sont fortement corrélés, la diversification peut avoir un impact limité sur la réduction du risque.</p>
</section>
<section id="c.-dans-un-plan-moyenne-variance-représentez-les-9-séries." class="level4">
<h4 class="anchored" data-anchor-id="c.-dans-un-plan-moyenne-variance-représentez-les-9-séries.">c.&nbsp;Dans un plan moyenne-variance, représentez les 9 séries.</h4>
</section>
<section id="d.-déduisez-en-les-titres-inefficients." class="level4">
<h4 class="anchored" data-anchor-id="d.-déduisez-en-les-titres-inefficients.">d.&nbsp;Déduisez-en les titres inefficients.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les moyennes et les covariances des rendements de chaque série</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>means <span class="ot">&lt;-</span> <span class="fu">sapply</span>(returns, mean)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>covariances <span class="ot">&lt;-</span> <span class="fu">cov</span>(returns)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les rendements moyens et les variances pour chaque série</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>portfolios <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> means,</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">var =</span> <span class="fu">diag</span>(covariances)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Tracer les rendements moyens en fonction des variances pour chaque série</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(portfolios<span class="sc">$</span>var, portfolios<span class="sc">$</span>mean, </span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Variance"</span>, <span class="at">ylab =</span> <span class="st">"Rendement moyen"</span>,</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Plan Moyenne-Variance des 9 séries"</span>)</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(portfolios<span class="sc">$</span>var, portfolios<span class="sc">$</span>mean, <span class="at">labels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">pos =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Dans un plan moyenne-variance, les titres inefficients sont généralement ceux qui se trouvent sur la frontière efficiente, c’est-à-dire les séries qui offrent le meilleur rendement pour un niveau donné de risque ou la plus faible variance pour un rendement donné.</p>
<p>Pour identifier les titres inefficients dans ce contexte, nous pouvons utiliser la théorie moderne du portefeuille pour déterminer la frontière efficiente. Les titres qui ne sont pas sur la frontière efficiente sont considérés comme inefficients.</p>
<p>Dans le graphique de la moyenne-variance que nous avons tracé, les titres qui ne sont pas sur la frontière efficiente peuvent être considérés comme inefficients. Ces titres sont ceux qui sont situés en dessous de la frontière efficiente et ne sont pas atteints par une combinaison linéaire des titres situés sur la frontière.</p>
</section>
</section>
<section id="considérez-dans-la-suite-les-trois-premiers-fonds-notamment-les-séries-amundi-cpr-climate-action-i-mainfirst-global-equities-x-et-the-andersons-ande." class="level3">
<h3 class="anchored" data-anchor-id="considérez-dans-la-suite-les-trois-premiers-fonds-notamment-les-séries-amundi-cpr-climate-action-i-mainfirst-global-equities-x-et-the-andersons-ande.">2. Considérez dans la suite les trois premiers fonds notamment les séries Amundi CPR Climate Action I, MainFirst Global Equities X et The Andersons : (ANDE).</h3>
<section id="a.-tracez-la-frontière-efficiente-à-partir-de-toutes-les-combinaisons-possibles-de-ces-trois-titres." class="level4">
<h4 class="anchored" data-anchor-id="a.-tracez-la-frontière-efficiente-à-partir-de-toutes-les-combinaisons-possibles-de-ces-trois-titres.">a. Tracez la frontière efficiente à partir de toutes les combinaisons possibles de ces trois titres.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sélectionner les rendements des trois premiers fonds</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>returns <span class="ot">&lt;-</span> <span class="fu">cbind</span>(data1_clean<span class="sc">$</span>Rendement, data2_clean<span class="sc">$</span>Rendement, data3_clean<span class="sc">$</span>Rendement)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les moyennes et les covariances des rendements des trois fonds</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>means <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(returns)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>covariances <span class="ot">&lt;-</span> <span class="fu">cov</span>(returns)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Nombre de simulations pour générer les poids des portefeuilles</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>num_simulations <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Générer des poids aléatoires pour chaque titre</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># Pour la reproductibilité</span></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>weights_combinations <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>), <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>), <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>weights_combinations <span class="ot">&lt;-</span> weights_combinations[<span class="fu">rowSums</span>(weights_combinations) <span class="sc">==</span> <span class="dv">1</span>, ]</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Nombre de combinaisons de poids</span></span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>num_combinations <span class="ot">&lt;-</span> <span class="fu">nrow</span>(weights_combinations)</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Générer des matrices de poids</span></span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>weights_matrices <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="dv">0</span>, <span class="at">dim =</span> <span class="fu">c</span>(num_combinations, <span class="fu">ncol</span>(returns)))</span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Remplir les matrices de poids</span></span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>num_combinations) {</span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a>  weights_matrices[i, ] <span class="ot">&lt;-</span> <span class="fu">t</span>(weights_combinations[i, ])</span>
<span id="cb48-25"><a href="#cb48-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb48-26"><a href="#cb48-26" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb48-27"><a href="#cb48-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les rendements des portefeuilles</span></span>
<span id="cb48-28"><a href="#cb48-28" aria-hidden="true" tabindex="-1"></a>portfolio_returns <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(weights_matrices <span class="sc">*</span> means)</span>
<span id="cb48-29"><a href="#cb48-29" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb48-30"><a href="#cb48-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les variances des portefeuilles</span></span>
<span id="cb48-31"><a href="#cb48-31" aria-hidden="true" tabindex="-1"></a>portfolio_variances <span class="ot">&lt;-</span> <span class="fu">diag</span>(weights_matrices <span class="sc">%*%</span> covariances <span class="sc">%*%</span> <span class="fu">t</span>(weights_matrices))</span>
<span id="cb48-32"><a href="#cb48-32" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb48-33"><a href="#cb48-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Tracer la frontière efficiente</span></span>
<span id="cb48-34"><a href="#cb48-34" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">sqrt</span>(portfolio_variances), portfolio_returns, <span class="at">type =</span> <span class="st">"l"</span>,</span>
<span id="cb48-35"><a href="#cb48-35" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Écart-type"</span>, <span class="at">ylab =</span> <span class="st">"Rendement"</span>,</span>
<span id="cb48-36"><a href="#cb48-36" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Frontière efficiente des trois premiers fonds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Projet_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="b.-déterminez-le-portefeuille-de-variance-minimale-et-calculer-le-rendement-attendu-et-lécart-type-de-ce-portefeuille.-y-a-t-il-des-pondérations-négatives-dans-le-portefeuille-de-variance-minimale" class="level4">
<h4 class="anchored" data-anchor-id="b.-déterminez-le-portefeuille-de-variance-minimale-et-calculer-le-rendement-attendu-et-lécart-type-de-ce-portefeuille.-y-a-t-il-des-pondérations-négatives-dans-le-portefeuille-de-variance-minimale">b. Déterminez le portefeuille de variance minimale et calculer le rendement attendu et l’écart-type de ce portefeuille. Y a-t-il des pondérations négatives dans le portefeuille de variance minimale ?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger la bibliothèque</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quadprog)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Sélectionner les rendements des trois premiers fonds</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>returns <span class="ot">&lt;-</span> <span class="fu">cbind</span>(data1_clean<span class="sc">$</span>Rendement, data2_clean<span class="sc">$</span>Rendement, data3_clean<span class="sc">$</span>Rendement)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les moyennes et les covariances des rendements des trois fonds</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>means <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(returns)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>covariances <span class="ot">&lt;-</span> <span class="fu">cov</span>(returns)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer l'inverse de la matrice de covariance</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>inv_cov <span class="ot">&lt;-</span> <span class="fu">solve</span>(covariances)</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les pondérations du portefeuille de variance minimale</span></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">ncol</span>(returns)</span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>portfolio_weights <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, n) <span class="sc">%*%</span> inv_cov <span class="sc">/</span> <span class="fu">sum</span>(<span class="fu">rep</span>(<span class="dv">1</span>, n) <span class="sc">%*%</span> inv_cov)</span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer le rendement attendu du portefeuille de variance minimale</span></span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a>min_variance_return <span class="ot">&lt;-</span> <span class="fu">sum</span>(means <span class="sc">*</span> portfolio_weights)</span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer l'écart-type du portefeuille de variance minimale</span></span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a>min_variance_sd <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(portfolio_weights <span class="sc">%*%</span> covariances <span class="sc">%*%</span> <span class="fu">t</span>(portfolio_weights))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Les pondérations du portefeuille de variance minimale sont de 0.669 pour le premier fonds, 0.267 pour le deuxième fonds et 0.064 pour le troisième fonds. Le rendement attendu de ce portefeuille est d’environ 0.0008385 et l’écart-type est d’environ 0.0061817.</p>
<p>Il n’y a pas de pondérations négatives dans le portefeuille de variance minimale. Cela est dû à la contrainte de somme des pondérations égale à 1, qui garantit que les pondérations restent positives.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Pondérations du portefeuille de variance minimale :"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          [,1]      [,2]       [,3]
[1,] 0.6694603 0.2668298 0.06370993</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Rendement attendu du portefeuille de variance minimale : 0.000838488909801793"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Écart-type du portefeuille de variance minimale : 0.00618173541293812"</code></pre>
</div>
</div>
</section>
<section id="c.-en-prenant-pour-rendement-de-lactif-sans-risque-𝑟𝑓-25-déterminez-le-portefeuille-tangent." class="level4">
<h4 class="anchored" data-anchor-id="c.-en-prenant-pour-rendement-de-lactif-sans-risque-𝑟𝑓-25-déterminez-le-portefeuille-tangent.">c.&nbsp;En prenant pour rendement de l’actif sans risque 𝑟𝑓 = 2,5%, déterminez le portefeuille tangent.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rendement de l'actif sans risque</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>rf <span class="ot">&lt;-</span> <span class="fl">0.025</span>  <span class="co"># 2.5%</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculer les pondérations du portefeuille tangent</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>tangent_weights <span class="ot">&lt;-</span> <span class="fu">solve</span>(covariances) <span class="sc">%*%</span> (means <span class="sc">-</span> rf) <span class="sc">/</span> <span class="fu">sum</span>(<span class="fu">solve</span>(covariances) <span class="sc">%*%</span> (means <span class="sc">-</span> rf))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Pondérations du portefeuille tangent :"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>           [,1]
[1,] 0.67645036
[2,] 0.26471571
[3,] 0.05883394</code></pre>
</div>
</div>
<p>Cela signifie que pour obtenir le portefeuille tangent avec un rendement sans risque de 2,5%, nous devrions allouer 67,645% de notre portefeuille au premier actif, 26,472% au deuxième actif et 5,883% au troisième actif.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>