project:
  type: website
  output-dir: docs

website:
  title: "Data da vezañ tretet"
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/paulnest

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

