project:
  type: website
  output-dir: docs

website:
  title: "Data et beurre salé"
  - parametre_blog.qmd
  navbar:
    right:
      - parametre_blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/paulnest

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

