{
  "hash": "18cc9a51f5db4be0a72220ea96ecbd7f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Biostatistique\"\nauthor: \"Paul Nestour et Lauriane Belane-Tanga\"\nformat: html\neditor: visual\ndate: \"2024-02-16\"\ncategories: [dossier]\nimage: \"voiture.jpeg\"\n---\n\n\n## Analyse et Optimisation d'un trajet de voiture\n\n### Introduction\n\nUn individu du nom de Kevin DUNN utilise une application pour suivre les coordonnées GPS lorsqu'il se rend au travail et en revient chaque jour. L'application calcule **la distance parcourue (en kilomètres)** en prenant en compte les données de localisation et d'altitude. Elle calcule également **les vitesses moyennes et maximales** en prenant en compte **le temps de mouvement et d'arrêt de la voiture**; ainsi que **la durée totale du trajet**. M. Dunn a également répertorié **la date et l'heure** à laquelle il commence son trajet, le sens dans lequel il l'effectue, **s'il a pris ou non l'autoroute** en entière et quelques **commentaires**. Nous n'avons pas le détail du calcul effectué par ailleurs, le conducteur a également calculé **sa consommation** d'essence durant chaque trajet. **Monsieur Dunn souhaite optimiser sa consommation d'essence durant chaque trajet, pour ainsi effectuer des économies en réduisant les coûts liés au carburant et participer à la réduction des émissions de carbone**. Nous allons donc analyser près de **205 trajets** effectués par M. Dunn sur une période de 6 mois entre juillet 2011 et janvier 2012.\n\nNous avons 13 variables explicatives : AvgMovingSpeed, la vitesse moyenne enregistrée lorsque la voiture est en mouvement ; AvgSpeed : la vitesse moyenne pour l'ensemble du trajet ; Distance : parcourue en kilomètres ; FuelEconomy : l'estimation de l'économie de carburant ; MaxSpeed : la vitesse la plus rapide enregistrée ; MovingTime : durée pendant laquelle la voiture a été considérée comme en déplacement ; TotalTime : durée de l'ensemble du trajet en minutes ; Take407All : oui si l'autoroute 407 a été empruntée durant le trajet mais il essaie d'éviter ; Comments ; Date des voyages ; StartTime lors de l'entrée dans la voiture ; GoingTo : work or home, le sens de la marche ; DayOfWeek : de lundi à vendredi.\n\nAu cours de notre analyse, il sera question pour nous d'analyser les informations recueillies de M. Dunn de manière adaptée et d'interpréter correctement les résultats afin de fournir à M. Dunn des résultats et des stratégies pour qu'il réussisse à mieux gérer ses consommations.\n\nDe plus, l'analyse de ses données ne se limite pas à une exploration de ses habitudes de déplacement. Pour lui présenter des résultats concrets et fiables, nous allons analyser les facteurs qui influencent l'efficacité énergétique. En ces temps où la durabilité et la responsabilité environnementales occupent une place centrale dans nos préoccupations, cette analyse pourrait s'avérer précieuse non seulement pour M. Dunn mais aussi pour d'autres agents économiques en leur permettant de contribuer activement à la réduction des émissions de gaz à effet de serre.\n\nLe dossier du jeu de données, de sa description et le contact de M. Dunn sont accessibles sur le site : <https://openmv.net/> sous le nom de \"Travel times\".\n\n### Les librairies utilisées\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(mice)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(RColorBrewer)\nlibrary(tidyr)\nlibrary(outliers)\nlibrary(corrplot)\nlibrary(caret)\nlibrary(viridis)\n```\n:::\n\n\n### Les Données\n\n#### Ouverture des données et visualisation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntravel_times <- read_excel(\"./data/travel-times.xlsx\")\nView(travel_times)\nTravel=travel_times\n```\n:::\n\n\n### Nettoyage des données : remplacement des tirets par NA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTravel$FuelEconomy <- gsub(\"-\", NA, Travel$FuelEconomy)\nView(Travel)\n```\n:::\n\n\n### Modification du format des variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTravel$StartTime<- format(Travel$StartTime, \"%H:%M:%S\")\nTravel$Date <- as.Date(Travel$Date, format = \"%m/%d/%Y\")\nTravel$FuelEconomy <- as.numeric(Travel$FuelEconomy)\nView(Travel)\n```\n:::\n\n\n### Aperçu des données\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(Travel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Date             StartTime          DayOfWeek           GoingTo         \n Min.   :2011-07-11   Length:205         Length:205         Length:205        \n 1st Qu.:2011-08-22   Class :character   Class :character   Class :character  \n Median :2011-10-04   Mode  :character   Mode  :character   Mode  :character  \n Mean   :2011-10-05                                                           \n 3rd Qu.:2011-11-17                                                           \n Max.   :2012-01-06                                                           \n                                                                              \n    Distance        MaxSpeed        AvgSpeed      AvgMovingSpeed  \n Min.   :48.32   Min.   :112.2   Min.   : 38.10   Min.   : 50.30  \n 1st Qu.:50.65   1st Qu.:124.9   1st Qu.: 68.90   1st Qu.: 76.60  \n Median :51.14   Median :127.4   Median : 73.60   Median : 81.40  \n Mean   :50.99   Mean   :127.6   Mean   : 74.48   Mean   : 81.98  \n 3rd Qu.:51.63   3rd Qu.:129.8   3rd Qu.: 79.90   3rd Qu.: 86.00  \n Max.   :60.32   Max.   :140.9   Max.   :107.70   Max.   :112.10  \n NA's   :1       NA's   :1                                        \n  FuelEconomy       TotalTime       MovingTime     Take407All       \n Min.   : 7.810   Min.   :28.20   Min.   :27.10   Length:205        \n 1st Qu.: 8.370   1st Qu.:38.40   1st Qu.:35.67   Class :character  \n Median : 8.520   Median :41.25   Median :37.60   Mode  :character  \n Mean   : 8.691   Mean   :41.91   Mean   :37.86                     \n 3rd Qu.: 8.970   3rd Qu.:44.42   3rd Qu.:39.90                     \n Max.   :10.050   Max.   :82.30   Max.   :62.40                     \n NA's   :19       NA's   :1       NA's   :1                         \n   Comments        \n Length:205        \n Class :character  \n Mode  :character  \n                   \n                   \n                   \n                   \n```\n\n\n:::\n:::\n\n\nUn premier aperçu de notre jeu de données nous permet de constater ce qui suit :\n\n-   Nous avons 4 variables qualitatives : **comments**, **Take407All**, **GoingTo**, et **DayOfWeek**.\n-   Les données couvrent une période du 11 juillet 2011 au 06 janvier 2012.\n-   Les heures de départ sont stockées sous forme de chaînes de caractères mais ne sont pas utiles pour notre analyse.\n-   Les jours de la semaine où M. Dunn se déplace sont du lundi au vendredi.\n-   La distance des déplacements varie entre 48.32 et 60.32 km.\n-   La vitesse maximale pendant les déplacements varie entre 112.2 et 140.9 km/h.\n-   La consommation de carburant pendant les déplacements de M. Dunn ne peut pas encore être spécifiée car nous remarquons la présence de 19 valeurs manquantes.\n-   Le temps total des déplacements varie entre 28.20 et 82.30 minutes.\n-   Le temps passé en mouvement pendant les déplacements varie entre 27.10 et 62.40 minutes.\n\nNous décidons de ne pas tenir compte de la variable **comments** durant notre analyse car elle nous fournit simplement des informations supplémentaires sur la tenue des déplacements de M. Dunn.\n\n### Expulsion des colonnes comments et startTime.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubset_data <- Travel[, !colnames(Travel) %in% c( \"StartTime\")]\nsubset_data <- subset_data[, -12, drop = FALSE]\nView(subset_data)\nTravel=subset_data\nView(Travel)\n```\n:::\n\n\n### Visualisation des données manquantes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmd.pattern(Travel, rotate.names = TRUE)\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Date DayOfWeek GoingTo AvgSpeed AvgMovingSpeed Distance MaxSpeed TotalTime\n181    1         1       1        1              1        1        1         1\n19     1         1       1        1              1        1        1         1\n1      1         1       1        1              1        1        1         1\n1      1         1       1        1              1        1        1         1\n1      1         1       1        1              1        1        1         0\n1      1         1       1        1              1        1        0         1\n1      1         1       1        1              1        0        1         1\n       0         0       0        0              0        1        1         1\n    MovingTime Take407All FuelEconomy   \n181          1          1           1  0\n19           1          1           0  1\n1            1          0           1  1\n1            0          1           1  1\n1            1          1           1  1\n1            1          1           1  1\n1            1          1           1  1\n             1          1          19 24\n```\n\n\n:::\n:::\n\n\nLa visualisation des données nous permet de constater que nous avons 24 données manquantes, réparties comme suit : la variable FuelEconomy a 19 valeurs manquantes, et une valeur manquante respectivement pour les variables Distance, MaxSpeed, TotalTime, MovingTime, et Take407All.\n\nNous allons par la suite effectuer une analyse univariée, une analyse bivariée, et remplacer nos 24 valeurs manquantes.\n\n#### Calcul des données manquantes simples\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTravel$MovingTime[187] <- round((Travel$Distance[187] / Travel$AvgMovingSpeed[187])*60 ,1)\nTravel$Distance[155] <- round((Travel$MovingTime[155])*0.0167*(Travel$AvgMovingSpeed[155]),2)\nTravel$TotalTime[66] <- round((Travel$Distance[187] / Travel$AvgSpeed[187])*60 ,1)\n\nmd.pattern(Travel, rotate.names = TRUE)\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Date DayOfWeek GoingTo Distance AvgSpeed AvgMovingSpeed TotalTime\n184    1         1       1        1        1              1         1\n19     1         1       1        1        1              1         1\n1      1         1       1        1        1              1         1\n1      1         1       1        1        1              1         1\n       0         0       0        0        0              0         0\n    MovingTime MaxSpeed Take407All FuelEconomy   \n184          1        1          1           1  0\n19           1        1          1           0  1\n1            1        1          0           1  1\n1            1        0          1           1  1\n             0        1          1          19 21\n```\n\n\n:::\n:::\n\n\n## Analyse Univariée\n\n### Analyse des variables qualitatives\n\nLes 3 variables qualitatives sont : Take407All, GoingTo, et DayOfWeek. Nous allons réaliser des tableaux de contingence car nos variables sont finies.\n\n#### Tableaux de contingence\n\nNous utiliserons la fonction count() de la librairie **dplyr** car elle permet de voir les valeurs manquantes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(Travel,Take407All)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  Take407All     n\n  <chr>      <int>\n1 No           169\n2 Yes           35\n3 <NA>           1\n```\n\n\n:::\n\n```{.r .cell-code}\ncount(Travel,GoingTo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  GoingTo     n\n  <chr>   <int>\n1 GSK       105\n2 Home      100\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(Travel$DayOfWeek)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   Friday    Monday  Thursday   Tuesday Wednesday \n       27        39        44        48        47 \n```\n\n\n:::\n\n```{.r .cell-code}\ncount(Travel,DayOfWeek)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  DayOfWeek     n\n  <chr>     <int>\n1 Friday       27\n2 Monday       39\n3 Thursday     44\n4 Tuesday      48\n5 Wednesday    47\n```\n\n\n:::\n:::\n\n\nLa sortie indique le décompte du nombre d'occurrences de chaque valeur de la variable **Take407All**. Ainsi, nous pouvons dire que sur les 205 trajets effectués par M. Dunn, il emprunte l'autoroute 407 35 fois et ne l'emprunte pas 169 fois. De plus, parmi les 205 trajets, il y a un jour pour lequel nous ne savons pas par quelle voie M. Dunn roule, ce qui correspond à une donnée manquante. Nous la traiterons plus tard, à l'aide d'une régression linéaire et des variables **AvgSpeed**, **MaxSpeed** et **MovingTime**.\n\nDans ces 205 trajets, M. Dunn effectue 100 trajets de son lieu de travail vers sa maison et 105 trajets de sa maison vers son lieu de travail.\n\nEnfin, il se déplace durant 5 jours de la semaine, du lundi au vendredi. Plus précisément, il a effectué 27 trajets le vendredi, 39 trajets le lundi, 44 trajets le jeudi, 48 trajets le mardi, et 47 trajets le mercredi.\n\n**Nous constatons donc que durant les 6 mois, il s'est moins déplacé en voiture le vendredi**.\n\nNous décidons par la suite d'effectuer une représentation graphique pour mieux illustrer ces données.\n\n#### Représentation graphique\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTravel |>\n  ggplot() +\n  aes(x = Take407All , fill = Take407All ) +\n  geom_bar() +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\nTravel |>\n  ggplot() +\n  aes(x = GoingTo , fill = GoingTo ) +\n  geom_bar() +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n\n```{.r .cell-code}\nTravel |>\n  ggplot() +\n  aes(x = DayOfWeek , fill = DayOfWeek ) +\n  geom_bar() +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-10-3.png){width=672}\n:::\n:::\n\n\n### Analyse des variables Quantitatives\n\nNous allons explorer la dispersion de chacune de nos 8 variables quantitatives en utilisant des histogrammes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTravel |> \n  ggplot() +\n  aes(x = Distance) +\n  geom_histogram(binwidth = 1) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\nTravel |>\n  ggplot() +\n  aes(x = MaxSpeed  ) +\n  geom_histogram(binwidth = 1) +\n  theme_classic()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 1 row containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n\n```{.r .cell-code}\nTravel |>\n  ggplot() +\n  aes(x = AvgSpeed  ) +\n  geom_histogram(binwidth = 1) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-11-3.png){width=672}\n:::\n\n```{.r .cell-code}\nTravel |>\n  ggplot() +\n  aes(x = AvgMovingSpeed  ) +\n  geom_histogram(binwidth = 1) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-11-4.png){width=672}\n:::\n\n```{.r .cell-code}\nTravel |>\n  ggplot() +\n  aes(x = TotalTime ) +\n  geom_histogram(binwidth = 1) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-11-5.png){width=672}\n:::\n\n```{.r .cell-code}\nTravel |>\n  ggplot() +\n  aes(x =  MovingTime  ) +\n  geom_histogram(binwidth = 1) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-11-6.png){width=672}\n:::\n\n```{.r .cell-code}\nTravel |>\n  ggplot() +\n  aes(x =  FuelEconomy  ) +\n  geom_histogram() +\n  theme_classic()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 19 rows containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-11-7.png){width=672}\n:::\n:::\n\n\nNous générons ainsi les histogrammes des variables : FuelEconomy, MovingTime, TotalTime, AvgMovingSpeed, AvgSpeed, MaxSpeed, et Distance. Cela nous permet de visualiser la distribution des valeurs telles que la vitesse moyenne des déplacements, la vitesse la plus rapide enregistrée, l'estimation de l'économie du carburant, la distance parcourue en kilomètres, la durée de l'ensemble du trajet en minutes, et la vitesse moyenne pour l'ensemble des trajets. Comme constaté, ultérieurement certaines d'entre elles ont des valeurs manquantes. Aussi, La distribution de la variable économie de carburant est différente de celle des autres variables, probablement parce que les valeurs se répètent plusieur fois. En effet M. Dunn indique sur le site internet que le calcule de cette variable est imprécis sans donner de détails.\n\n### Cas particulier des dates\n\nDans notre cas, nous avons deux années d'études.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDayOfWeek <- c(\"lundi\", \"mardi\", \"mercredi\", \"jeudi\", \"vendredi\")\n\nggplot(Travel, aes(x = DayOfWeek, fill = DayOfWeek)) +\n  geom_bar(position = \"dodge\") +\n  facet_wrap(~ format(Date, \"%B\"), scales = \"free_x\") +  # Utiliser le nom complet du mois\n  theme_bw() +\n  labs(title = \"Nombre de trajets par jour de la semaine, réparti par mois\", \n       x = \"Jour de la semaine\", y = \"Nombre de trajets\", fill = \"Jour de la semaine\")\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nNous avons créé un graphique à barres montrant le nombre de trajets par jour de la semaine, avec les jours de la semaine réorganisés dans l'ordre spécifique.\n\n#### Cas particulier d'une valeur aberrante reperée visuellement\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTravel$AvgSpeedVar <- Travel$AvgSpeed - Travel$AvgMovingSpeed\nggplot(Travel, aes(x = Date)) +\n  geom_line(aes(y = AvgSpeed), color = \"blue\", linetype = \"solid\", size = 1) +\n  geom_line(aes(y = AvgMovingSpeed), color = \"red\", linetype = \"solid\", size = 1) +\n  theme_bw() + \n  labs(title = \"Variation de la vitesse moyenne totale et en mouvement au fil du temps\", \n       x = \"Date\", y = \"Vitesse\") +  \n  scale_x_date(date_labels = \"%Y-%m\", date_breaks = \"1 month\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nÀ l'aide de la nouvelle variable et des boxplots suivantes, nous pourrons décider de traiter ou non la valeur abberante en question que nous pouvons observer en Octobre 2011.\n\n### Boxplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTravel |>\n  pivot_longer(\n    cols = where(is.numeric)\n  ) |>\n  ggplot() +\n  aes( y = value) +\n  facet_wrap(~ name, scales = \"free_y\") +\n  geom_boxplot(na.rm = TRUE) +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Tratement de la valeur aberrante mentionnée précédemment\nTravel$AvgSpeed[99] <- round(Travel$Distance[99] / (Travel$TotalTime[99] / 60),1)\n\n#Suppression de la variable annexe\nTravel <- Travel[, -12]\n```\n:::\n\n\nOn observe que toutes nos variables quantitatives présentent des valeurs aberrantes : les boîtes à moustaches mettent en évidence ces valeurs atypiques. La variable FuelEconomy ne présente qu'une seule valeur aberrante, mais sa boîte à moustaches révèle une distribution asymétrique des données, avec une médiane plus proche du premier quartile. Nous remarquons ainsi que dans moins de la moitié de ses trajets, M. Dunn réalise une économie de carburant de 8.5 unités.\n\nLes autres variables ont plus de 3 valeurs aberrantes. Nous cherchons à comprendre la raison de ces valeurs atypiques, et décidons de les conserver pour une analyse plus approfondie de la consommation d'énergie et des déplacements de M. Dunn.\n\nNous passons ensuite à l'analyse bivariée de nos données.\n\n## Analyse bivariée\n\n### Analyse quanti-quanti\n\nL'objectif ici est de déterminer si l'une des variables peut être calculée à partir de l'autre. Plus précisément, nous tentons d'expliquer la corrélation entre deux variables quantitatives.\n\nNous représentons la matrice de corrélation, qui présente les coefficients de corrélation entre toutes les paires de variables de l'ensemble des données. Chaque cellule de la matrice représente le degré de corrélation entre deux variables spécifiques.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvariables_numeriques <- Travel[sapply(Travel, is.numeric)]\nmatrice_correlation <- cor(variables_numeriques, use = \"complete.obs\")\ncorrplot(matrice_correlation, type = \"upper\", order = \"hclust\",\n         addCoef.col = \"black\",\n         tl.col = \"black\", tl.srt = 90, tl.cex = 0.9, number.cex = 0.8,\n         diag = FALSE, col = brewer.pal(n = 9, name = \"Blues\"))\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nLes coefficients de corrélation varient de -1 à 1. Un coefficient de 1 indique une corrélation parfaite, ce qui signifie que lorsque la première variable augmente, la deuxième augmente également de manière linéaire. Un coefficient de 0 indique l'absence de corrélation linéaire entre les deux variables.\n\nDans notre cas, la variable **AvgSpeed** présente une forte corrélation positive avec la variable **AvgMovingSpeed**, avec un coefficient de **0.89**, et une forte corrélation négative avec **TotalTime** de **-0.87**. Cela signifie que lorsque la vitesse moyenne générale d'un trajet augmente, la vitesse moyenne pendant le mouvement augmente également ; et lorsque la vitesse moyenne générale augmente, le temps de trajet diminue. Ainsi, une vitesse élevée conduit à des temps de trajet plus courts.\n\nAvgMovingSpeed et MovingTime sont fortement corrélées négativement (-0.94), suggérant que lorsque la vitesse moyenne en mouvement augmente, le temps de déplacement total diminue, et vice versa. Cela peut être lié à l'efficacité des déplacements, à la fluidité de la circulation et/ou au style de conduite de M. Dunn.\n\n### Analyse quali-quali\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(Travel, GoingTo, DayOfWeek) |>\n  ggplot() +\n    aes(x = DayOfWeek, y = GoingTo, fill = n) +\n    geom_tile(stat = \"identity\") +\n    theme_light()\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncount(Travel, GoingTo,Take407All) |>\n  ggplot() +\n    aes(x = Take407All, y = GoingTo, fill = n) +\n    geom_tile(stat = \"identity\") +\n    theme_light()\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-16-2.png){width=672}\n:::\n:::\n\n\nNous avons généré deux heatmaps :\n\nLe premier représente graphiquement le nombre d'occurrences croisées entre les destinations (GoingTo) et les jours de la semaine (DayOfWeek). Chaque tuile dans le graphique correspond à une combinaison de destination et de jour de la semaine, et la couleur de la tuile indique le nombre d'occurrences pour cette combinaison.\n\nLe premier est censé représenter le nombre de trajets en fonction de la destination et des jours de la semaine. Cependant, au niveau des jours de la semaine, nous observons des cases NA, probablement dues à un problème au niveau du jeu de données.\n\n### Analyse quali-quanti\n\n#### Analyse avec la variable quali GoingTo\n\n\n::: {.cell}\n\n```{.r .cell-code}\npalette_couleurs <- colorRampPalette(c(\"red\", \"blue\", \"green\", \"purple\"))(length(unique(Travel$GoingTo)))\nvecteur_couleur <- setNames(palette_couleurs, unique(Travel$GoingTo))\nTravel |> \n  pivot_longer(\n    cols = Distance:MaxSpeed:TotalTime:AvgSpeed:AvgMovingSpeed:MovingTime:FuelEconomy ,\n    names_to = \"mesure\",\n    values_to = \"valeur\"\n  ) |> \n  ggplot() +\n  aes(y = valeur, x = GoingTo, color = GoingTo) +\n  geom_boxplot(alpha = 0.5) +\n  scale_color_manual(values = vecteur_couleur) +\n  facet_wrap(~ mesure, scales = \"free_y\") +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_text(size = 8),\n    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), \n    legend.position = \"right\"  \n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in x:y: numerical expression has 2 elements: only the first used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in x:y: numerical expression has 6 elements: only the first used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in x:y: numerical expression has 3 elements: only the first used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in x:y: numerical expression has 4 elements: only the first used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in x:y: numerical expression has 7 elements: only the first used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 20 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nNous avons généré un graphique à boîtes avec des boîtes à moustaches pour différentes mesures, organisées par destination (GoingTo) : en rouge lorsque M.Dunn rentre chez lui et en violet lorsqu'il se déplace vers son lieu de travail. Il y a plus d'une valeur aberrante par boîte. Les boîtes sont presque toutes asymétriques. Par exemple, pour la variable FuelEconomy, sur l'ensemble des trajets que M.Dunn effectue vers son lieu de travail (GSK), durant moins de la moitié des trajets, M.Dunn réalise une économie de carburant de 8.6 unités. La vitesse moyenne enregistrée lorsque la voiture est en déplacement durant moins de la moitié de ses trajets vers son lieu de travail (GSK) est de 80 minutes.\n\n#### Analyse avec la variable quali DayOfWeek\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTravel |> \n  pivot_longer(\n    cols = c(Distance, MaxSpeed, AvgMovingSpeed, TotalTime, FuelEconomy, AvgSpeed, MovingTime),\n    names_to = \"mesure\",\n    values_to = \"valeur\"\n  ) |> \n  ggplot() +\n  aes(y = valeur, x = DayOfWeek, color = as.factor(DayOfWeek)) +\n  geom_boxplot() +\n  geom_jitter(alpha = 0.3) +\n  facet_wrap(~ mesure, scales = \"free_y\") +\n  scale_color_manual(values = rainbow(length(unique(Travel$DayOfWeek)))) +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 20 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 20 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nIci, nous avons la représentation graphique avec des boîtes à moustaches de différentes mesures, organisées par jour de la semaine. Ainsi, durant les cinq premiers jours de la semaine, nous avons la vitesse maximale pendant les trajets pour chaque jour de la semaine, ainsi que les économies de carburant réalisées. Nous remarquons que pour moins de la moitié de ses trajets, M. Dunn effectue des économies d'environ 8.5 unités par jour et qu'il va plus rapidement le mardi.\n\n#### Analyse bivariée avec la variable qualitative Take407All\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTravel |>\n  pivot_longer(\n    cols = Distance:MaxSpeed:AvgMovingSpeed:TotalTime:FuelEconomy :AvgSpeed:MovingTime ,\n    names_to = \"mesure\",\n    values_to = \"valeur\"\n  ) |>\n  ggplot() +\n  aes(y = valeur, x = Take407All, color = Take407All) +\n  geom_boxplot() +\n  geom_jitter(alpha = 0.3) +\n  facet_wrap(~ mesure, scales = \"free_y\") +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in x:y: numerical expression has 2 elements: only the first used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in x:y: numerical expression has 4 elements: only the first used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in x:y: numerical expression has 6 elements: only the first used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in x:y: numerical expression has 5 elements: only the first used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in x:y: numerical expression has 3 elements: only the first used\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 20 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 20 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nIci, nous avons la représentation des boîtes en fonction de l'emprunt ou non du péage 407. La boîte grise représente les valeurs manquantes. On peut observer que M. Dunn est plus rapide lorsqu'il emprunte l'autoroute. Les distances parcourues sont plus courtes et, pour la plupart de ses trajets effectués sur l'autoroute, il réalise une économie de carburant de 8.3 unités. De plus, le temps mis pour effectuer un trajet est plus court lorsqu'il emprunte l'autoroute.\n\n### Traitement de la variable FuelEconmy et de la valeur manquante MaxSpeed\n\nPour la vitesse maximale du trajet ligne 170 et pour les 19 valeurs manquantes nous faisons à nouveau appel au package mice.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntables_imputation <- mice(Travel, m=5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n iter imp variable\n  1   1  MaxSpeed  FuelEconomy\n  1   2  MaxSpeed  FuelEconomy\n  1   3  MaxSpeed  FuelEconomy\n  1   4  MaxSpeed  FuelEconomy\n  1   5  MaxSpeed  FuelEconomy\n  2   1  MaxSpeed  FuelEconomy\n  2   2  MaxSpeed  FuelEconomy\n  2   3  MaxSpeed  FuelEconomy\n  2   4  MaxSpeed  FuelEconomy\n  2   5  MaxSpeed  FuelEconomy\n  3   1  MaxSpeed  FuelEconomy\n  3   2  MaxSpeed  FuelEconomy\n  3   3  MaxSpeed  FuelEconomy\n  3   4  MaxSpeed  FuelEconomy\n  3   5  MaxSpeed  FuelEconomy\n  4   1  MaxSpeed  FuelEconomy\n  4   2  MaxSpeed  FuelEconomy\n  4   3  MaxSpeed  FuelEconomy\n  4   4  MaxSpeed  FuelEconomy\n  4   5  MaxSpeed  FuelEconomy\n  5   1  MaxSpeed  FuelEconomy\n  5   2  MaxSpeed  FuelEconomy\n  5   3  MaxSpeed  FuelEconomy\n  5   4  MaxSpeed  FuelEconomy\n  5   5  MaxSpeed  FuelEconomy\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Number of logged events: 3\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(tables_imputation)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nClass: mids\nNumber of multiple imputations:  5 \nImputation methods:\n          Date      DayOfWeek        GoingTo       Distance       MaxSpeed \n            \"\"             \"\"             \"\"             \"\"          \"pmm\" \n      AvgSpeed AvgMovingSpeed    FuelEconomy      TotalTime     MovingTime \n            \"\"             \"\"          \"pmm\"             \"\"             \"\" \n    Take407All \n            \"\" \nPredictorMatrix:\n          Date DayOfWeek GoingTo Distance MaxSpeed AvgSpeed AvgMovingSpeed\nDate         0         0       0        1        1        1              1\nDayOfWeek    1         0       0        1        1        1              1\nGoingTo      1         0       0        1        1        1              1\nDistance     1         0       0        0        1        1              1\nMaxSpeed     1         0       0        1        0        1              1\nAvgSpeed     1         0       0        1        1        0              1\n          FuelEconomy TotalTime MovingTime Take407All\nDate                1         1          1          0\nDayOfWeek           1         1          1          0\nGoingTo             1         1          1          0\nDistance            1         1          1          0\nMaxSpeed            1         1          1          0\nAvgSpeed            1         1          1          0\nNumber of logged events:  3 \n  it im dep     meth        out\n1  0  0     constant  DayOfWeek\n2  0  0     constant    GoingTo\n3  0  0     constant Take407All\n```\n\n\n:::\n\n```{.r .cell-code}\nTravel <- complete(tables_imputation, sample(1:5,1))\nmd.pattern(Travel, rotate.names = TRUE)\n```\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Date DayOfWeek GoingTo Distance MaxSpeed AvgSpeed AvgMovingSpeed\n204    1         1       1        1        1        1              1\n1      1         1       1        1        1        1              1\n       0         0       0        0        0        0              0\n    FuelEconomy TotalTime MovingTime Take407All  \n204           1         1          1          1 0\n1             1         1          1          0 1\n              0         0          0          1 1\n```\n\n\n:::\n:::\n\n\nPour les deux colonnes, mice utilise la méthode de la PMM (Predictive Mean Matching), pour les deux variables quantitatives. Il calcule 5 valeurs pour chaque cellule vide. Enfin, à l'aide de la fonction sample, je recrée un dataframe complet avec des valeurs imputée aléatoirement.\n\n### Régression logistique\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(caret)\n\nTrajet <- Travel[complete.cases(Travel$Take407All), ]\n\nTrajet$Take407All <- ifelse(Trajet$Take407All == \"Yes\", 1, 0)\n\nmodel <- glm(Take407All ~ MaxSpeed + AvgSpeed + MovingTime, \n              data = Trajet,\n              family = binomial)\n\nmissing_data <- Travel[is.na(Travel$Take407All), c(\"MaxSpeed\", \"AvgSpeed\", \"MovingTime\")]\n\npredictions <- predict(model, newdata = missing_data, type = \"response\")\n\nTravel$Take407All[is.na(Travel$Take407All)] <- round(predictions)\n\nTravel$Take407All <- ifelse(Travel$Take407All == \"Yes\", 1, 0)\n\nTravel$Take407All <- as.factor(Travel$Take407All)\n\nmd.pattern(Travel, rotate.names = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n /\\     /\\\n{  `---'  }\n{  O   O  }\n==>  V <==  No need for mice. This data set is completely observed.\n \\  \\|/  /\n  `-----'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Projet-travel-times_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Date DayOfWeek GoingTo Distance MaxSpeed AvgSpeed AvgMovingSpeed\n205    1         1       1        1        1        1              1\n       0         0       0        0        0        0              0\n    FuelEconomy TotalTime MovingTime Take407All  \n205           1         1          1          1 0\n              0         0          0          0 0\n```\n\n\n:::\n:::\n\n\nÀ partir d'un dataframe où il n'y a plus de valeurs manquantes, nous effectuons une régression logistoque afin de déterminer qu'elle est la valeur de la ligne 71 de la colonne Take407All. Grâce à la fonction **predict** du package **stats** Nous trouvons que la valeur manquante était \"No\". La prédiction est correct. Il aurait été intéressant de réaliser une matrice de confusion pour évaluer le modèle de prédiction.\n",
    "supporting": [
      "Projet-travel-times_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}